import type {IntakeState} from './intake';import type {ProductFactoryState} from './product-factory';import type {PricingState} from './pricing';import type {OrderState} from './orders';
export type IntelligenceDimension={key:string;label:string;orders:number;revenue:number;cost:number;contribution:number;marginPercent:number|null};
export type TrendEvidence={label:'SEM_DADOS'|'SEM_JANELA'|'ACELERANDO'|'ESTAVEL'|'DESACELERANDO';recent:{from:string|null;to:string|null;orders:number;revenue:number};previous:{from:string|null;to:string|null;orders:number;revenue:number};thresholdPercent:number;statement:string};
export type IntelligenceReport={totals:IntelligenceDimension;byProduct:IntelligenceDimension[];byOffer:IntelligenceDimension[];byOrigin:IntelligenceDimension[];byCategory:IntelligenceDimension[];byPeriod:IntelligenceDimension[];trend:TrendEvidence;feedback:string[]};
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;
function dimension(key:string,label:string,rows:{salePrice:number;costSnapshot:number}[]):IntelligenceDimension{const revenue=round(rows.reduce((s,o)=>s+o.salePrice,0));const cost=round(rows.reduce((s,o)=>s+o.costSnapshot,0));const contribution=round(revenue-cost);return{key,label,orders:rows.length,revenue,cost,contribution,marginPercent:revenue?round(contribution/revenue*100):null}}
function group(rows:Enriched[],key:(r:Enriched)=>string,label:(r:Enriched)=>string){const result=new Map<string,{label:string;rows:Enriched[]}>();for(const row of rows){const k=key(row);const item=result.get(k)??{label:label(row),rows:[]};item.rows.push(row);result.set(k,item)}return[...result].map(([k,v])=>dimension(k,v.label,v.rows)).sort((a,b)=>b.revenue-a.revenue)}
type Enriched={salePrice:number;costSnapshot:number;createdAt:string;productId:string;productLabel:string;offer:string;origin:string;category:string};
export function buildIntelligence(intake:IntakeState,products:ProductFactoryState,pricing:PricingState,orders:OrderState,now=new Date()):IntelligenceReport{const rows:Enriched[]=orders.orders.filter(o=>o.status==='ENVIADO').map(order=>{const product=products.products.find(p=>p.id===order.productId);const candidate=intake.candidates.find(c=>c.id===product?.candidateId);const calc=pricing.calculations.find(c=>c.productId===order.productId&&c.approval==='APROVADO');return{...order,productLabel:product?.universalTitle??order.productId,offer:calc?.offerId??'Sem oferta',origin:candidate?.source??'Sem origem',category:product?.category||candidate?.category||'Sem categoria'}});
  const cutoff=new Date(now);cutoff.setUTCDate(cutoff.getUTCDate()-7);const previousCutoff=new Date(cutoff);previousCutoff.setUTCDate(previousCutoff.getUTCDate()-7);const recentRows=rows.filter(r=>new Date(r.createdAt)>=cutoff&&new Date(r.createdAt)<=now);const previousRows=rows.filter(r=>new Date(r.createdAt)>=previousCutoff&&new Date(r.createdAt)<cutoff);const recent=dimension('recent','Atual',recentRows);const previous=dimension('previous','Anterior',previousRows);let label:TrendEvidence['label']='SEM_DADOS';let statement='Nenhuma venda enviada nas janelas avaliadas.';if(recent.orders||previous.orders){if(!previous.revenue){label='SEM_JANELA';statement='Há dados recentes, mas não existe base anterior para comparação.'}else{const variation=(recent.revenue-previous.revenue)/previous.revenue;if(variation>.05){label='ACELERANDO';statement=`Receita avançou ${round(variation*100)}% sobre a janela anterior.`}else if(variation<-.05){label='DESACELERANDO';statement=`Receita recuou ${Math.abs(round(variation*100))}% sobre a janela anterior.`}else{label='ESTAVEL';statement='Receita variou dentro da faixa neutra de 5%.'}}}
  const feedback:string[]=[];const totals=dimension('all','Total',rows);if(totals.marginPercent!==null&&totals.marginPercent<15)feedback.push('Margem realizada abaixo de 15%; revisar custos e pricing na Triagem.');if(label==='DESACELERANDO')feedback.push('Desaceleração detectada; revisar evidências de origem e categoria em Trends.');if(!feedback.length)feedback.push(rows.length?'Operação sem alerta informativo no período.':'Aguardar pedidos enviados para gerar feedback econômico.');
  const period=(r:Enriched)=>r.createdAt.slice(0,7);return{totals,byProduct:group(rows,r=>r.productId,r=>r.productLabel),byOffer:group(rows,r=>r.offer,r=>r.offer),byOrigin:group(rows,r=>r.origin,r=>r.origin),byCategory:group(rows,r=>r.category,r=>r.category),byPeriod:group(rows,period,period),trend:{label,recent:{from:cutoff.toISOString(),to:now.toISOString(),orders:recent.orders,revenue:recent.revenue},previous:{from:previousCutoff.toISOString(),to:cutoff.toISOString(),orders:previous.orders,revenue:previous.revenue},thresholdPercent:5,statement},feedback};
}
