import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID } from 'node:crypto';
import { getDatabasePool } from './server-state';
export type IntegrationKind='SUPPLIER'|'CHANNEL'|'PROVIDER';
export type IntegrationStatus='DRAFT'|'CONFIGURED'|'TESTED'|'ACTIVE'|'ERROR'|'DISABLED';
export type IntegrationInput={kind:IntegrationKind;providerKey:string;name:string;environment?:'SANDBOX'|'PRODUCTION';config?:Record<string,string>;secrets?:Record<string,string>;capabilities?:string[]};
function key(){const value=process.env.DDF_CREDENTIALS_KEY;if(!value)throw new Error('DDF_CREDENTIALS_KEY não configurada.');return createHash('sha256').update(value).digest()}
function encrypt(value:Record<string,string>){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key(),iv);const body=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64')}
function decrypt(value:string|null){if(!value)return{};const raw=Buffer.from(value,'base64');const decipher=createDecipheriv('aes-256-gcm',key(),raw.subarray(0,12));decipher.setAuthTag(raw.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(raw.subarray(28)),decipher.final()]).toString('utf8')) as Record<string,string>}
function publicRow(row:Record<string,unknown>){return{id:row.id,kind:row.kind,providerKey:row.provider_key,name:row.name,environment:row.environment,status:row.status,config:row.config??{},secretFields:row.secret_fields??[],capabilities:row.capabilities??[],lastTestedAt:row.last_tested_at,lastError:row.last_error,createdAt:row.created_at,updatedAt:row.updated_at}}
export async function listIntegrations(){const db=await getDatabasePool();const [items,bindings,tests]=await Promise.all([db.query('SELECT * FROM integration_configs ORDER BY updated_at DESC'),db.query(`SELECT id,brand_name AS "brandName",store_name AS "storeName",integration_id AS "integrationId",status,created_at AS "createdAt",updated_at AS "updatedAt" FROM brand_store_bindings ORDER BY updated_at DESC`),db.query(`SELECT id,integration_id AS "integrationId",status,message,checked_at AS "checkedAt" FROM integration_test_runs ORDER BY checked_at DESC LIMIT 50`)]);return{items:items.rows.map(publicRow),bindings:bindings.rows,tests:tests.rows}}
export async function createIntegration(input:IntegrationInput,actor:string,correlationId:string){const db=await getDatabasePool();const id=randomUUID();const secrets=input.secrets??{};const fields=Object.keys(secrets).filter(k=>secrets[k]);const status=fields.length?'CONFIGURED':'DRAFT';const result=await db.query(`INSERT INTO integration_configs(id,kind,provider_key,name,environment,status,config,encrypted_secrets,secret_fields,capabilities) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[id,input.kind,input.providerKey,input.name,input.environment??'PRODUCTION',status,JSON.stringify(input.config??{}),fields.length?encrypt(secrets):null,JSON.stringify(fields),JSON.stringify(input.capabilities??[])]);await db.query(`INSERT INTO audit_events(id,actor,action,entity_type,entity_id,correlation_id,after_state,metadata) VALUES($1,$2,'INTEGRATION_CREATED','INTEGRATION',$3,$4,$5,$6)`,[randomUUID(),actor,id,correlationId,JSON.stringify(publicRow(result.rows[0])),JSON.stringify({secretFields:fields})]);return publicRow(result.rows[0])}
export async function updateIntegration(id:string,input:Partial<IntegrationInput>&{status?:IntegrationStatus},actor:string,correlationId:string){const db=await getDatabasePool();const current=await db.query('SELECT * FROM integration_configs WHERE id=$1',[id]);if(!current.rows[0])return null;const old=current.rows[0];const oldSecrets=decrypt(old.encrypted_secrets);const supplied=Object.fromEntries(Object.entries(input.secrets??{}).filter(([,v])=>v));const secrets={...oldSecrets,...supplied};const fields=Object.keys(secrets);const result=await db.query(`UPDATE integration_configs SET name=$2,environment=$3,status=$4,config=$5,encrypted_secrets=$6,secret_fields=$7,capabilities=$8,updated_at=now() WHERE id=$1 RETURNING *`,[id,input.name??old.name,input.environment??old.environment,input.status??old.status,JSON.stringify(input.config??old.config),fields.length?encrypt(secrets):null,JSON.stringify(fields),JSON.stringify(input.capabilities??old.capabilities)]);await db.query(`INSERT INTO audit_events(id,actor,action,entity_type,entity_id,correlation_id,before_state,after_state) VALUES($1,$2,'INTEGRATION_UPDATED','INTEGRATION',$3,$4,$5,$6)`,[randomUUID(),actor,id,correlationId,JSON.stringify(publicRow(old)),JSON.stringify(publicRow(result.rows[0]))]);return publicRow(result.rows[0])}
export async function testIntegration(id:string){const db=await getDatabasePool();const result=await db.query('SELECT * FROM integration_configs WHERE id=$1',[id]);if(!result.rows[0])return null;const row=result.rows[0];let success=true;let message='Configuração e credenciais disponíveis para o adaptador.';try{const secrets=decrypt(row.encrypted_secrets);if(!Object.keys(secrets).length){success=false;message='Inclua ao menos uma credencial antes de testar.'}}catch{success=false;message='Não foi possível abrir o cofre de credenciais.'}const status=success?'TESTED':'ERROR';const runId=randomUUID();await db.query(`INSERT INTO integration_test_runs(id,integration_id,status,message) VALUES($1,$2,$3,$4)`,[runId,id,success?'SUCCEEDED':'FAILED',message]);await db.query(`UPDATE integration_configs SET status=$2,last_tested_at=now(),last_error=$3,updated_at=now() WHERE id=$1`,[id,status,success?'':message]);return{success,message,status,runId}}
export async function createBinding(input:{brandName:string;storeName:string;integrationId?:string|null}){const db=await getDatabasePool();const result=await db.query(`INSERT INTO brand_store_bindings(id,brand_name,store_name,integration_id,status) VALUES($1,$2,$3,$4,'INACTIVE') RETURNING id,brand_name AS "brandName",store_name AS "storeName",integration_id AS "integrationId",status`,[randomUUID(),input.brandName,input.storeName,input.integrationId||null]);return result.rows[0]}
