import { randomUUID } from 'node:crypto';
import { getDatabasePool } from './server-state';
import { getProviderAdapter } from './providers';
import type { SupplierAdapter } from './providers/types';
import { decryptIntegrationSecrets, encryptIntegrationSecrets, integrationStatusForSecrets, serializePublicIntegration } from './integration-security';
export { decryptIntegrationSecrets, encryptIntegrationSecrets, integrationStatusForSecrets, serializePublicIntegration } from './integration-security';
import type { IntegrationStatus } from './integration-security';
export type { IntegrationStatus } from './integration-security';
export type IntegrationKind='SUPPLIER'|'CHANNEL'|'PROVIDER';
export type IntegrationInput={kind:IntegrationKind;providerKey:string;name:string;environment?:'SANDBOX'|'PRODUCTION';config?:Record<string,string>;secrets?:Record<string,string>;capabilities?:string[]};
const MANUAL_STATUSES=new Set<IntegrationStatus>(['ACTIVE','DISABLED']);
export function validateIntegrationInput(input:Partial<IntegrationInput>){
 if(input.name!==undefined&&!input.name.trim())throw new Error('O nome da integração é obrigatório.');
 if(input.environment!==undefined&&!['SANDBOX','PRODUCTION'].includes(input.environment))throw new Error('Ambiente inválido.');
 for(const [field,value]of Object.entries(input.config??{}))if(typeof value!=='string'||value.length>2000)throw new Error(`Configuração inválida: ${field}.`);
 for(const [field,value]of Object.entries(input.secrets??{}))if(typeof value!=='string'||value.length>8000)throw new Error(`Credencial inválida: ${field}.`);
}
const encrypt=encryptIntegrationSecrets;
const decrypt=decryptIntegrationSecrets;
const publicRow=serializePublicIntegration;
export async function listIntegrations(){const db=await getDatabasePool();const [items,bindings,tests]=await Promise.all([db.query('SELECT * FROM integration_configs ORDER BY updated_at DESC'),db.query(`SELECT id,brand_name AS "brandName",store_name AS "storeName",integration_id AS "integrationId",status,created_at AS "createdAt",updated_at AS "updatedAt" FROM brand_store_bindings ORDER BY updated_at DESC`),db.query(`SELECT id,integration_id AS "integrationId",status,message,checked_at AS "checkedAt" FROM integration_test_runs ORDER BY checked_at DESC LIMIT 50`)]);return{items:items.rows.map(publicRow),bindings:bindings.rows,tests:tests.rows}}
export async function createIntegration(input:IntegrationInput,actor:string,correlationId:string){validateIntegrationInput(input);const db=await getDatabasePool();const id=randomUUID();const secrets=input.secrets??{};const fields=Object.keys(secrets).filter(k=>secrets[k]);const status=integrationStatusForSecrets(secrets);const result=await db.query(`INSERT INTO integration_configs(id,kind,provider_key,name,environment,status,config,encrypted_secrets,secret_fields,capabilities) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[id,input.kind,input.providerKey,input.name,input.environment??'PRODUCTION',status,JSON.stringify(input.config??{}),fields.length?encrypt(secrets):null,JSON.stringify(fields),JSON.stringify(input.capabilities??[])]);await db.query(`INSERT INTO audit_events(id,actor,action,entity_type,entity_id,correlation_id,after_state,metadata) VALUES($1,$2,'INTEGRATION_CREATED','INTEGRATION',$3,$4,$5,$6)`,[randomUUID(),actor,id,correlationId,JSON.stringify(publicRow(result.rows[0])),JSON.stringify({secretFields:fields})]);return publicRow(result.rows[0])}
export async function updateIntegration(id:string,input:Partial<IntegrationInput>&{status?:IntegrationStatus},actor:string,correlationId:string){validateIntegrationInput(input);const db=await getDatabasePool();const current=await db.query('SELECT * FROM integration_configs WHERE id=$1',[id]);if(!current.rows[0])return null;const old=current.rows[0];if(input.status&&!MANUAL_STATUSES.has(input.status))throw new Error('A situação só pode ser alterada usando testar, ativar ou desativar.');if(input.status==='ACTIVE'&&(!['TESTED','DISABLED'].includes(old.status)||!old.last_tested_at||old.last_error))throw new Error('Teste esta configuração com sucesso antes de ativá-la.');const oldSecrets=decrypt(old.encrypted_secrets);const supplied=Object.fromEntries(Object.entries(input.secrets??{}).filter(([,v])=>v));const secrets={...oldSecrets,...supplied};const fields=Object.keys(secrets);const changesConnection=input.config!==undefined||input.secrets!==undefined||input.environment!==undefined||input.capabilities!==undefined;const status=changesConnection?integrationStatusForSecrets(secrets):(input.status??old.status);const result=await db.query(`UPDATE integration_configs SET name=$2,environment=$3,status=$4,config=$5,encrypted_secrets=$6,secret_fields=$7,capabilities=$8,last_tested_at=$9,last_error=$10,updated_at=now() WHERE id=$1 RETURNING *`,[id,input.name??old.name,input.environment??old.environment,status,JSON.stringify(input.config??old.config),fields.length?encrypt(secrets):null,JSON.stringify(fields),JSON.stringify(input.capabilities??old.capabilities),changesConnection?null:old.last_tested_at,changesConnection?'Configuração alterada; execute um novo teste.':old.last_error]);await db.query(`INSERT INTO audit_events(id,actor,action,entity_type,entity_id,correlation_id,before_state,after_state) VALUES($1,$2,'INTEGRATION_UPDATED','INTEGRATION',$3,$4,$5,$6)`,[randomUUID(),actor,id,correlationId,JSON.stringify(publicRow(old)),JSON.stringify(publicRow(result.rows[0]))]);return publicRow(result.rows[0])}
export async function testIntegration(id:string){const db=await getDatabasePool();const result=await db.query('SELECT * FROM integration_configs WHERE id=$1',[id]);if(!result.rows[0])return null;const row=result.rows[0];let success=true;let message='Configuração e credenciais disponíveis para o adaptador.';try{const secrets=decrypt(row.encrypted_secrets);const adapter=getProviderAdapter(row.provider_key,row.config??{},secrets,row.environment??'SANDBOX');if(adapter){const r=await adapter.test();success=r.ok;message=r.message;}else{if(!Object.keys(secrets).length){success=false;message='Inclua ao menos uma credencial antes de testar.'}}}catch{success=false;message='Não foi possível abrir o cofre de credenciais.'}const status=success?'TESTED':'ERROR';const runId=randomUUID();await db.query(`INSERT INTO integration_test_runs(id,integration_id,status,message) VALUES($1,$2,$3,$4)`,[runId,id,success?'SUCCEEDED':'FAILED',message]);await db.query(`UPDATE integration_configs SET status=$2,last_tested_at=now(),last_error=$3,updated_at=now() WHERE id=$1`,[id,status,success?'':message]);return{success,message,status,runId}}
export async function createBinding(input:{brandName:string;storeName:string;integrationId?:string|null}){const db=await getDatabasePool();const result=await db.query(`INSERT INTO brand_store_bindings(id,brand_name,store_name,integration_id,status) VALUES($1,$2,$3,$4,'INACTIVE') RETURNING id,brand_name AS "brandName",store_name AS "storeName",integration_id AS "integrationId",status`,[randomUUID(),input.brandName,input.storeName,input.integrationId||null]);return result.rows[0]}

export async function getSupplierAdapterForIntegration(id:string):Promise<{adapter:SupplierAdapter;name:string}|null>{
 const db=await getDatabasePool();
 const result=await db.query("SELECT * FROM integration_configs WHERE id=$1 AND kind='SUPPLIER'",[id]);
 const row=result.rows[0]; if(!row)return null;
 if(!['TESTED','ACTIVE'].includes(row.status))throw new Error('Teste a integração do fornecedor antes de consultar produtos.');
 const adapter=getProviderAdapter(row.provider_key,row.config??{},decrypt(row.encrypted_secrets),row.environment??'PRODUCTION');
 if(!adapter||!('searchProducts' in adapter))throw new Error('Este fornecedor ainda não oferece consulta de produtos.');
 return{adapter:adapter as SupplierAdapter,name:String(row.name)};
}
