export type OrderStatus='RECEBIDO'|'VALIDADO'|'EM_FULFILLMENT'|'ENVIADO'|'EXCECAO'|'CANCELADO'|'RECUSADO';
export type ExceptionCategory='PAGAMENTO'|'ESTOQUE'|'ENDERECO'|'FORNECEDOR'|'FRAUDE'|'INTEGRACAO'|'OUTRO';
export type ExceptionResolution='RECUPERAR'|'CANCELAR'|'RECUSAR';
export type Order={id:string;externalOrderId:string;productId:string;status:OrderStatus;salePrice:number;costSnapshot:number;currency:string;tracking:string;customerRef?:string;createdAt:string;updatedAt:string;retentionUntil:string;exceptionReason?:string;exceptionCategory?:ExceptionCategory;previousStatus?:Exclude<OrderStatus,'EXCECAO'|'CANCELADO'|'RECUSADO'>;resolutionNote?:string};
export type OrderState={version:1;orders:Order[];processedExternalIds:string[]};export const ORDER_STORAGE_KEY='ddf.orders.demo.v1';export const DEFAULT_RETENTION_DAYS=90;export const emptyOrders:OrderState={version:1,orders:[],processedExternalIds:[]};
function clean(value:string,max=160){return value.trim().replace(/[\u0000-\u001f\u007f]/g,'').slice(0,max)}
export function retentionDate(at:string,days=DEFAULT_RETENTION_DAYS){const parsed=Date.parse(at);const date=new Date(Number.isFinite(parsed)?parsed:Date.now());date.setUTCDate(date.getUTCDate()+days);return date.toISOString()}
export function receiveOrder(state:OrderState,input:Omit<Order,'id'|'status'|'tracking'|'createdAt'|'updatedAt'|'retentionUntil'>,id:string,at:string):OrderState{const externalOrderId=clean(input.externalOrderId);const customerRef=clean(input.customerRef??'',100);if(!externalOrderId||state.processedExternalIds.includes(externalOrderId))throw new Error('Pedido externo ausente ou já processado.');if(input.salePrice<=0||input.costSnapshot<0)throw new Error('Snapshot econômico inválido.');if(customerRef&&/[@+]|\d{8,}/.test(customerRef))throw new Error('Use somente uma referência opaca; não informe e-mail, telefone ou documento.');const order:Order={...input,externalOrderId,customerRef:customerRef||undefined,id,status:'RECEBIDO',tracking:'',createdAt:at,updatedAt:at,retentionUntil:retentionDate(at)};return{...state,orders:[order,...state.orders],processedExternalIds:[externalOrderId,...state.processedExternalIds]}}
const transitions:Record<OrderStatus,OrderStatus[]>={RECEBIDO:['VALIDADO','EXCECAO'],VALIDADO:['EM_FULFILLMENT','EXCECAO'],EM_FULFILLMENT:['ENVIADO','EXCECAO'],ENVIADO:[],EXCECAO:[],CANCELADO:[],RECUSADO:[]};
export function advanceOrder(state:OrderState,id:string,status:OrderStatus,at:string,tracking=''):OrderState{const o=state.orders.find(x=>x.id===id);if(!o||!transitions[o.status].includes(status))throw new Error('Transição de pedido inválida.');if(status==='ENVIADO'&&!tracking.trim())throw new Error('Tracking obrigatório para marcar como enviado.');return{...state,orders:state.orders.map(x=>x.id===id?{...x,status,tracking:clean(tracking,120),updatedAt:at}:x)}}
export function flagOrderException(state:OrderState,id:string,reason:string,at:string,category:ExceptionCategory='OUTRO'):OrderState{const order=state.orders.find(x=>x.id===id);if(!order||['ENVIADO','EXCECAO','CANCELADO','RECUSADO'].includes(order.status))throw new Error('Pedido indisponível para exceção.');if(!reason.trim())throw new Error('Motivo da exceção obrigatório.');const previousStatus=order.status as Exclude<OrderStatus,'EXCECAO'|'CANCELADO'|'RECUSADO'>;return{...state,orders:state.orders.map(x=>x.id===id?{...x,previousStatus,status:'EXCECAO',exceptionCategory:category,exceptionReason:clean(reason,500),updatedAt:at}:x)}}
export function resolveOrderException(state:OrderState,id:string,at:string,resolution:ExceptionResolution='RECUPERAR',note=''):OrderState{const order=state.orders.find(x=>x.id===id);if(!order||order.status!=='EXCECAO'||!order.previousStatus)throw new Error('Exceção indisponível para resolução.');const status=resolution==='RECUPERAR'?order.previousStatus:resolution==='CANCELAR'?'CANCELADO':'RECUSADO';return{...state,orders:state.orders.map(x=>x.id===id?{...x,status,previousStatus:undefined,exceptionReason:undefined,exceptionCategory:undefined,resolutionNote:clean(note,500)||undefined,updatedAt:at}:x)}}
export function purgeExpiredOrderData(state:OrderState,at:string):OrderState{const now=Date.parse(at);return{...state,orders:state.orders.map(order=>Date.parse(order.retentionUntil||retentionDate(order.createdAt))<=now?{...order,customerRef:undefined,resolutionNote:undefined,exceptionReason:order.status==='EXCECAO'?order.exceptionReason:undefined}:order)}}
