export type RateSource={provider:string;version:string;effectiveAt:string;reference?:string};
export type PricingSources={fx:RateSource;tax:RateSource;tariff:RateSource};
export const controlledPricingSources:PricingSources={fx:{provider:'DDF controlled input',version:'manual-v1',effectiveAt:'user-supplied'},tax:{provider:'DDF controlled input',version:'manual-v1',effectiveAt:'user-supplied'},tariff:{provider:'DDF controlled input',version:'manual-v1',effectiveAt:'user-supplied'}};
export type PricingInput={productId:string;supplierCost:number;shipping:number;taxes:number;fixedFees:number;channelFeePercent:number;paymentFeePercent:number;operatingCost:number;reserve:number;targetMarginPercent:number;minimumMarginPercent:number;currency:string;country?:string;channel?:string;store?:string;offerId?:string;fxRate?:number;sources?:PricingSources};
export type PriceCalculation=PricingInput&{id:string;version:number;totalFixedCost:number;variableRate:number;suggestedPrice:number|null;minimumSafePrice:number|null;status:'CALCULADO'|'BLOQUEADO'|'QUARENTENA';reason:string;at:string;approval:'PENDENTE'|'APROVADO';approvedAt?:string;approvedBy?:string};
export type PricingState={version:1;calculations:PriceCalculation[]};export const PRICING_STORAGE_KEY='ddf.pricing.demo.v1';export const emptyPricing:PricingState={version:1,calculations:[]};
export const roundMoney=(value:number,minorUnits=2)=>{if(!Number.isInteger(minorUnits)||minorUnits<0||minorUnits>4)throw new Error('Precisão monetária inválida.');const factor=10**minorUnits;return Math.round((value+Number.EPSILON)*factor)/factor};
const context=(c:Pick<PriceCalculation,'country'|'channel'|'store'|'offerId'|'currency'>)=>`${c.country??''}|${c.channel??''}|${c.store??''}|${c.offerId??''}|${c.currency}`;
export function calculatePrice(state:PricingState,input:PricingInput,id:string,at:string):PricingState{const values=Object.entries(input).filter(([,v])=>typeof v==='number').map(([,v])=>v as number);if(values.some(v=>!Number.isFinite(v)||v<0)||!input.currency.trim())throw new Error('Preencha todos os componentes com valores válidos.');if(!input.productId.trim())throw new Error('Produto obrigatório.');const fxRate=input.fxRate??1;if(!Number.isFinite(fxRate)||fxRate<=0)throw new Error('Taxa de câmbio inválida.');if(input.channelFeePercent>100||input.paymentFeePercent>100||input.targetMarginPercent>100||input.minimumMarginPercent>100)throw new Error('Percentuais não podem superar 100%.');const totalFixedCost=roundMoney((input.supplierCost+input.shipping)*fxRate+input.taxes+input.fixedFees+input.operatingCost+input.reserve);const variableRate=(input.channelFeePercent+input.paymentFeePercent)/100;const target=input.targetMarginPercent/100;const minimum=input.minimumMarginPercent/100;let status:PriceCalculation['status']='CALCULADO';let reason='';if(totalFixedCost<=0){status='BLOQUEADO';reason='Custo real ausente.'}else if(target<minimum){status='BLOQUEADO';reason='Margem alvo abaixo da margem mínima.'}else if(variableRate+target>=1||variableRate+minimum>=1){status='BLOQUEADO';reason='Taxas e margem tornam o cálculo inviável.'}let suggestedPrice=status==='CALCULADO'?roundMoney(totalFixedCost/(1-variableRate-target)):null;let minimumSafePrice=status==='CALCULADO'?roundMoney(totalFixedCost/(1-variableRate-minimum)):null;if(suggestedPrice!==null&&(!Number.isFinite(suggestedPrice)||suggestedPrice>Number.MAX_SAFE_INTEGER/100)){status='BLOQUEADO';reason='Resultado fora do limite monetário seguro.';suggestedPrice=null;minimumSafePrice=null}const previous=state.calculations.find(c=>c.productId===input.productId&&context(c)===context(input));if(status==='CALCULADO'&&previous?.suggestedPrice&&suggestedPrice&&Math.abs(suggestedPrice-previous.suggestedPrice)/previous.suggestedPrice>.3){status='QUARENTENA';reason='Variação superior a 30% exige análise de impacto.'}const version=(previous?.version??0)+1;return{...state,calculations:[{...input,sources:input.sources??controlledPricingSources,id,version,totalFixedCost,variableRate,suggestedPrice,minimumSafePrice,status,reason,at,approval:'PENDENTE'},...state.calculations]}}
export function approvePrice(state:PricingState,id:string,actor:string,at:string):PricingState{const calculation=state.calculations.find(item=>item.id===id);if(!calculation||calculation.status!=='CALCULADO')throw new Error('Somente cálculo seguro pode ser aprovado.');if(!actor.trim())throw new Error('Aprovador obrigatório.');return{...state,calculations:state.calculations.map(item=>item.id===id?{...item,approval:'APROVADO',approvedAt:at,approvedBy:actor.trim()}:item)}}
export function releaseQuarantine(state:PricingState,id:string,actor:string,reason:string):PricingState{const calculation=state.calculations.find(item=>item.id===id);if(!calculation||calculation.status!=='QUARENTENA')throw new Error('Cálculo não está em quarentena.');if(!actor.trim()||reason.trim().length<10)throw new Error('Informe aprovador e justificativa de ao menos 10 caracteres.');return{...state,calculations:state.calculations.map(item=>item.id===id?{...item,status:'CALCULADO',reason:`Quarentena liberada por ${actor.trim()}: ${reason.trim()}`,approval:'PENDENTE'}:item)}}
