import test from 'node:test';
import assert from 'node:assert/strict';
import { addSupplierOffer, assignProduct, catalogRecords, emptyCatalog, filterCatalog, upsertParty } from '../src/lib/catalog.ts';

const product = { id:'p1',candidateId:'c1',status:'PRONTO',version:3,universalTitle:'Óculos Solar',shortDescription:'Proteção diária',longDescription:'Produto universal',category:'Moda > Acessórios',bullets:['a','b','c'],benefits:['a','b'],tags:['uv400'],spec:{variants:[{id:'v1',sku:'SOL-01',title:'Preto',gtin:'',attributes:{cor:'preto'},dimensions:{lengthCm:null,widthCm:null,heightCm:null},weightGrams:null}],materials:['resina'],colors:['preto'],sizes:[],seo:{title:'',description:''},compliance:{notes:'',certifications:[]},localizations:{},destinationGaps:{marketplace:['GTIN ausente']}},createdAt:'now',updatedAt:'now' };

test('catálogo contém apenas produtos prontos e agrega dimensões relacionadas',()=>{let state=upsertParty(emptyCatalog,'store',{id:'loja-1',name:'Loja 1',active:true});state=assignProduct(state,'p1',{brandIds:['dilix','dilix'],storeIds:['loja-1'],destinations:['marketplace']},'now');state=addSupplierOffer(state,{productId:'p1',supplierName:'Fornecedor neutro',supplierRef:'A-1',cost:20,currency:'brl',stock:5,leadTimeDays:3},'o1','now');const draft={...product,id:'p2',status:'EM_PRODUCAO'};const records=catalogRecords(state,[product,draft],[],[],[]);assert.equal(records.length,1);assert.equal(records[0].brands[0].name,'Dilix');assert.equal(records[0].stores[0].name,'Loja 1');assert.equal(records[0].offers[0].currency,'BRL');assert.deepEqual(records[0].assignment.brandIds,['dilix']);});
test('filtros combinam busca, taxonomia, marca, loja, destino e gaps',()=>{let state=upsertParty(emptyCatalog,'store',{id:'loja-1',name:'Loja 1',active:true});state=assignProduct(state,'p1',{brandIds:['dilix'],storeIds:['loja-1'],destinations:['marketplace']},'now');const records=catalogRecords(state,[product],[],[],[]);assert.equal(filterCatalog(records,{query:'SOL-01',category:'Moda > Acessórios',brandId:'dilix',storeId:'loja-1',destination:'marketplace',gapsOnly:true}).length,1);assert.equal(filterCatalog(records,{query:'inexistente'}).length,0);});
test('oferta inválida ou duplicada é bloqueada',()=>{const input={productId:'p1',supplierName:'Fornecedor',supplierRef:'A-1',cost:20,currency:'BRL',stock:2,leadTimeDays:1};const state=addSupplierOffer(emptyCatalog,input,'o1','now');assert.throws(()=>addSupplierOffer(state,input,'o2','later'),/já existe/);assert.throws(()=>addSupplierOffer(emptyCatalog,{...input,cost:-1},'o1','now'),/valores válidos/);});
