import test from'node:test';import assert from'node:assert/strict';import{supplierCandidateInput,validateSupplierSearch}from'../src/lib/supplier-product.ts';
const product={itemId:'1005001234567890',title:'Óculos polarizado',price:12.5,currency:'USD',imageUrl:'https://ae01.alicdn.com/image.jpg',detailUrl:'https://www.aliexpress.com/item/1005001234567890.html',stock:8};
test('valida limites da consulta ao fornecedor',()=>{assert.equal(validateSupplierSearch(' oculos ',20),'oculos');assert.throws(()=>validateSupplierSearch('x',20),/2 e 120/);assert.throws(()=>validateSupplierSearch('oculos',51),/1 a 50/)});
test('mapeia produto para entrada auditável sem credenciais',()=>{const input=supplierCandidateInput(product,'AliExpress principal');assert.equal(input.url,product.detailUrl);assert.match(input.notes,/1005001234567890/);assert.equal(JSON.stringify(input).includes('accessToken'),false)});
test('bloqueia URL que não pertence ao AliExpress',()=>{assert.throws(()=>supplierCandidateInput({...product,detailUrl:'https://evil.example/item/1'},'Fornecedor'),/não pertence/)});

test('nome com mais de 160 caracteres é truncado e o completo fica em fullName',async()=>{const{addCandidate,emptyIntake}=await import('../src/lib/intake.ts');const long='Mochila impermeável '.repeat(12).trim();assert.ok(long.length>160);const input=supplierCandidateInput({...product,title:long},'AliExpress');assert.equal(Array.from(input.name).length,160);assert.ok(input.name.endsWith('…'));assert.equal(input.fullName,long);const state=addCandidate(emptyIntake,input,'c1','2026-09-26T00:00:00Z');assert.equal(state.candidates[0].fullName,long);assert.equal(state.candidates[0].name,input.name)});
test('nome curto não gera fullName e emojis não são cortados ao meio',async()=>{const{truncateName}=await import('../src/lib/intake.ts');const input=supplierCandidateInput(product,'AliExpress');assert.equal(input.name,product.title);assert.equal('fullName' in input,false);const emoji='😀'.repeat(200);const cut=truncateName(emoji);assert.equal(Array.from(cut).length,160);assert.equal(cut.isWellFormed(),true);assert.equal(truncateName('a'.repeat(160)),'a'.repeat(160))});
test('importação guarda dados estruturados do fornecedor (custo, estoque, fotos, variantes)',()=>{const input=supplierCandidateInput({...product,images:['https://ae01.alicdn.com/image.jpg','https://ae01.alicdn.com/2.jpg'],variants:[{sku:'s1',label:'Preto',price:12.5,stock:8,imageUrl:''}]},'AliExpress principal');assert.equal(input.supplier.cost,12.5);assert.equal(input.supplier.stock,8);assert.deepEqual(input.supplier.images,['https://ae01.alicdn.com/image.jpg','https://ae01.alicdn.com/2.jpg']);assert.equal(input.supplier.variants.length,1);assert.equal(input.supplier.name,'AliExpress principal')});
