'use client';

import { useState, useSyncExternalStore } from 'react';
import { catalogRecords, CATALOG_STORAGE_KEY, emptyCatalog, filterCatalog, type CatalogState, type SupplierOffer } from '@/lib/catalog';
import { command, errorMessage, sendCommand, type Command } from '@/lib/command-client';
import { emptyMedia, MEDIA_STORAGE_KEY, type MediaState } from '@/lib/media-factory';
import { emptyProductFactory, PRODUCT_STORAGE_KEY, productGaps, type ProductFactoryState } from '@/lib/product-factory';
import { emptyPricing, PRICING_STORAGE_KEY, type PricingState } from '@/lib/pricing';

const eventName = 'ddf-catalog-change';
const keys = [PRODUCT_STORAGE_KEY, MEDIA_STORAGE_KEY, PRICING_STORAGE_KEY, CATALOG_STORAGE_KEY];
function subscribe(callback: () => void) { const events = ['storage', 'ddf-products-change', 'ddf-media-change', 'ddf-pricing-change', eventName]; events.forEach(name => window.addEventListener(name, callback)); return () => events.forEach(name => window.removeEventListener(name, callback)); }
function snapshot() { try { return JSON.stringify(keys.map(key => localStorage.getItem(key) ?? '')); } catch { return 'unavailable'; } }
function parse(raw: string | null) {
  if (!raw) return { factory: emptyProductFactory, media: emptyMedia, pricing: emptyPricing, catalog: emptyCatalog };
  const [productsRaw, mediaRaw, pricingRaw, catalogRaw] = JSON.parse(raw) as string[];
  const factory: ProductFactoryState = productsRaw ? JSON.parse(productsRaw) : emptyProductFactory;
  const media: MediaState = mediaRaw ? JSON.parse(mediaRaw) : emptyMedia;
  const pricing: PricingState = pricingRaw ? JSON.parse(pricingRaw) : emptyPricing;
  const catalog: CatalogState = catalogRaw ? JSON.parse(catalogRaw) : emptyCatalog;
  if (factory.version !== 1 || media.version !== 1 || pricing.version !== 1 || catalog.version !== 1 || !Array.isArray(catalog.assignments)) throw new Error();
  return { factory, media, pricing, catalog };
}
const list = (value: FormDataEntryValue | null) => String(value ?? '').split(',').map(item => item.trim()).filter(Boolean);
const money = (value: number, currency: string) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: currency || 'BRL' }).format(value);

export function CatalogWorkspace() {
  const raw = useSyncExternalStore(subscribe, snapshot, () => null);
  let data = { factory: emptyProductFactory, media: emptyMedia, pricing: emptyPricing, catalog: emptyCatalog }; let loadError = '';
  try { data = parse(raw); } catch { loadError = 'O catálogo não pôde ser lido. A edição foi bloqueada para proteger os dados.'; }
  const [filters, setFilters] = useState({ query: '', category: '', brandId: '', storeId: '', destination: '', gapsOnly: false });
  const [expanded, setExpanded] = useState<string | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const allRecords = catalogRecords(data.catalog, data.factory.products, data.media.assets, data.pricing.calculations, data.factory.events);
  const records = filterCatalog(allRecords, filters);
  const categories = [...new Set(allRecords.map(item => item.product.category).filter(Boolean))].sort();
  const destinations = [...new Set([...allRecords.flatMap(item => item.assignment.destinations), ...allRecords.flatMap(item => Object.keys(item.destinationGaps))])].sort();
  function act(cmd: Command, success: string) { sendCommand(cmd).then(() => { setError(''); setMessage(success); }, cause => setError(errorMessage(cause))); }
  return <div className="space-y-6">
    <header><p className="eyebrow">Catálogo central / distribuição futura</p><h1 className="display-title">Produtos Disponíveis</h1><p className="lede">Produtos mestres prontos, com qualidade, variantes, mídia, ofertas, custos, destinos, gaps e associações comerciais — sem publicar automaticamente.</p></header>
    {(error || loadError) && <p role="alert" className="border border-red-300 bg-red-50 p-4 text-red-800">{error || loadError}</p>}<p role="status" className="text-sm text-green-800">{message}</p>
    <section className="surface grid gap-4 p-5 md:grid-cols-3 xl:grid-cols-6" aria-label="Filtros do catálogo">
      <label className="md:col-span-2">Buscar produto, tag, SKU ou variante<input className="ddf-input" value={filters.query} onChange={event => setFilters({ ...filters, query: event.target.value })} /></label>
      <Filter label="Categoria" value={filters.category} options={categories.map(value => [value, value])} onChange={category => setFilters({ ...filters, category })} />
      <Filter label="Marca" value={filters.brandId} options={data.catalog.brands.map(item => [item.id, item.name])} onChange={brandId => setFilters({ ...filters, brandId })} />
      <Filter label="Loja" value={filters.storeId} options={data.catalog.stores.map(item => [item.id, item.name])} onChange={storeId => setFilters({ ...filters, storeId })} />
      <Filter label="Destino" value={filters.destination} options={destinations.map(value => [value, value])} onChange={destination => setFilters({ ...filters, destination })} />
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={filters.gapsOnly} onChange={event => setFilters({ ...filters, gapsOnly: event.target.checked })} /> Somente com gaps</label>
      <button className="ddf-button secondary" onClick={() => setFilters({ query: '', category: '', brandId: '', storeId: '', destination: '', gapsOnly: false })}>Limpar filtros</button>
    </section>
    <section className="grid gap-4 md:grid-cols-3"><Metric label="Produtos prontos" value={allRecords.length} /><Metric label="Ofertas cadastradas" value={data.catalog.offers.length} /><Metric label="Resultado dos filtros" value={records.length} /></section>
    {!loadError && <PartyManager catalog={data.catalog} onSave={(kind, id, name) => act(command('catalog.upsertParty', { kind, id, name, active: true }), `${kind === 'brand' ? 'Marca' : 'Loja'} cadastrada.`)} />}
    {records.length === 0 && <div className="surface p-8"><h2 className="text-lg font-semibold">Nenhum produto encontrado</h2><p className="mt-2 text-gray-600">Finalize um Master Product ou ajuste os filtros do catálogo.</p></div>}
    {records.map(record => {
      const product = record.product; const variants = product.spec?.variants ?? []; const approvedMedia = record.media.filter(item => item.status === 'APROVADA'); const gaps = [...productGaps(product), ...Object.entries(record.destinationGaps).flatMap(([destination, items]) => items.map(item => `${destination}: ${item}`))];
      return <article key={product.id} className="surface overflow-hidden"><div className="grid gap-5 p-6 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded bg-green-100 px-2 py-1 text-green-900">Pronto</span><span className="rounded bg-stone-200 px-2 py-1">{product.category || 'Sem categoria'}</span><span className="rounded bg-stone-200 px-2 py-1">Versão {product.version}</span></div><h2 className="mt-3 text-2xl font-semibold">{product.universalTitle}</h2><p className="mt-2 text-gray-600">{product.shortDescription}</p><div className="mt-4 flex flex-wrap gap-4 text-sm"><strong>{variants.length} variante(s)</strong><strong>{approvedMedia.length} mídia(s) aprovada(s)</strong><strong>{record.offers.length} oferta(s)</strong><strong>{record.assignment.destinations.length} destino(s)</strong></div></div><button className="ddf-button secondary" aria-expanded={expanded === product.id} onClick={() => setExpanded(expanded === product.id ? null : product.id)}>{expanded === product.id ? 'Fechar detalhes' : 'Ver detalhes'}</button></div>
      {expanded === product.id && <div className="border-t border-stone-200 p-6"><div className="grid gap-6 lg:grid-cols-2">
        <Detail title="Variantes e atributos">{variants.length ? variants.map(item => <div key={item.id} className="border-t border-stone-200 py-3 text-sm"><strong>{item.title || item.sku}</strong><p>SKU {item.sku} · GTIN {item.gtin || 'não informado'} · {item.weightGrams ?? '—'} g</p><p>{Object.entries(item.attributes).map(([key, value]) => `${key}: ${value}`).join(' · ') || 'Sem atributos adicionais'}</p></div>) : <Empty text="Nenhuma variante cadastrada." />}</Detail>
        <Detail title="Mídia aprovada">{approvedMedia.length ? approvedMedia.map(item => <a className="block border-t border-stone-200 py-3 text-sm underline" href={item.url} target="_blank" rel="noreferrer" key={item.id}>{item.purpose} · {item.kind} · {item.mimeType || 'formato não informado'}</a>) : <Empty text="Nenhuma mídia aprovada." />}</Detail>
        <Detail title="Ofertas e custos">{record.offers.length ? record.offers.map(item => <div className="border-t border-stone-200 py-3 text-sm" key={item.id}><strong>{item.supplierName} · {item.supplierRef}</strong><p>{money(item.cost, item.currency)} · estoque {item.stock ?? 'não informado'} · prazo {item.leadTimeDays ?? '—'} dias</p></div>) : <Empty text="Nenhuma Supplier Offer cadastrada." />}<OfferForm productId={product.id} onSave={input => act(command('catalog.addOffer', { ...input }), 'Oferta cadastrada sem acionar o fornecedor.')} /></Detail>
        <Detail title="Pricing disponível">{record.prices.length ? record.prices.map(item => <div className="border-t border-stone-200 py-3 text-sm" key={item.id}><strong>{item.channel || 'Sem canal'} · {item.store || 'Sem loja'} · {item.status}</strong><p>Custo real {money(item.totalFixedCost, item.currency)} · sugerido {item.suggestedPrice === null ? 'bloqueado' : money(item.suggestedPrice, item.currency)}</p></div>) : <Empty text="Nenhum cálculo de preço." />}</Detail>
        <Detail title="Destinos e gaps"><p className="text-sm"><strong>Elegíveis:</strong> {record.assignment.destinations.join(', ') || 'nenhum selecionado'}</p>{gaps.length ? <ul className="mt-2 list-disc pl-5 text-sm text-amber-800">{gaps.map(item => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-green-800">Sem gaps registrados.</p>}</Detail>
        <Detail title="Histórico">{record.history.length ? record.history.map(item => <p className="border-t border-stone-200 py-2 text-sm" key={item.id}>{item.action.replaceAll('_', ' ')} · versão {item.version} · {new Date(item.at).toLocaleString('pt-BR')}</p>) : <Empty text="Sem eventos registrados." />}</Detail>
      </div><AssignmentForm productId={product.id} assignment={record.assignment} brands={data.catalog.brands} stores={data.catalog.stores} onSave={input => act(command('catalog.assignProduct', { productId: product.id, ...input }), 'Associações e destinos atualizados. Nenhuma publicação foi iniciada.')} /></div>}
      </article>;
    })}
  </div>;
}

function Filter({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label>{label}<select className="ddf-input" value={value} onChange={event => onChange(event.target.value)}><option value="">Todos</option>{options.map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="surface p-5"><p className="text-sm text-gray-600">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></div>; }
function Detail({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="text-lg font-semibold">{title}</h3><div className="mt-3">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="text-sm text-gray-600">{text}</p>; }
function PartyManager({ catalog, onSave }: { catalog: CatalogState; onSave: (kind: 'brand'|'store', id: string, name: string) => void }) { return <details className="surface p-5"><summary className="cursor-pointer font-semibold">Gerenciar marcas e lojas</summary><p className="mt-2 text-sm text-gray-600">Dimensões comerciais reutilizáveis. Um produto pode pertencer a várias marcas e lojas.</p><form className="mt-4 grid gap-3 md:grid-cols-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name')); const id = name.trim().toLocaleLowerCase().replace(/[^a-z0-9]+/g, '-'); onSave(String(form.get('kind')) as 'brand'|'store', id, name); event.currentTarget.reset(); }}><label>Tipo<select name="kind" className="ddf-input"><option value="brand">Marca</option><option value="store">Loja</option></select></label><label>Nome<input name="name" required className="ddf-input" /></label><button className="ddf-button self-end">Cadastrar dimensão</button></form><p className="mt-4 text-sm">Marcas: {catalog.brands.map(item => item.name).join(', ') || '—'} · Lojas: {catalog.stores.map(item => item.name).join(', ') || '—'}</p></details>; }
function AssignmentForm({ productId, assignment, brands, stores, onSave }: { productId: string; assignment: { brandIds: string[]; storeIds: string[]; destinations: string[] }; brands: CatalogState['brands']; stores: CatalogState['stores']; onSave: (input: { brandIds: string[]; storeIds: string[]; destinations: string[] }) => void }) { return <form className="mt-6 grid gap-4 border-t border-stone-200 pt-6 md:grid-cols-3" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ brandIds: form.getAll('brands').map(String), storeIds: form.getAll('stores').map(String), destinations: list(form.get('destinations')) }); }}><fieldset><legend className="font-semibold">Marcas</legend>{brands.map(item => <label className="mt-2 flex gap-2 text-sm" key={item.id}><input type="checkbox" name="brands" value={item.id} defaultChecked={assignment.brandIds.includes(item.id)} />{item.name}</label>)}</fieldset><fieldset><legend className="font-semibold">Lojas</legend>{stores.map(item => <label className="mt-2 flex gap-2 text-sm" key={item.id}><input type="checkbox" name="stores" value={item.id} defaultChecked={assignment.storeIds.includes(item.id)} />{item.name}</label>)}{stores.length === 0 && <Empty text="Cadastre uma loja acima." />}</fieldset><label>Destinos elegíveis — separados por vírgula<input key={`${productId}:${assignment.destinations.join('|')}`} name="destinations" className="ddf-input" defaultValue={assignment.destinations.join(', ')} /><button className="ddf-button mt-4">Salvar associações</button></label></form>; }
function OfferForm({ productId, onSave }: { productId: string; onSave: (input: Omit<SupplierOffer, 'id' | 'updatedAt'>) => void }) { return <details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">Cadastrar Supplier Offer</summary><form className="mt-3 grid gap-3 text-sm sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const nullable = (name: string) => String(form.get(name)).trim() === '' ? null : Number(form.get(name)); onSave({ productId, supplierName: String(form.get('supplierName')), supplierRef: String(form.get('supplierRef')), cost: Number(form.get('cost')), currency: String(form.get('currency')), stock: nullable('stock'), leadTimeDays: nullable('leadTimeDays') }); event.currentTarget.reset(); }}><label>Fornecedor<input required name="supplierName" className="ddf-input" /></label><label>Referência<input required name="supplierRef" className="ddf-input" /></label><label>Custo<input required name="cost" type="number" min="0" step="0.01" className="ddf-input" /></label><label>Moeda<input required name="currency" defaultValue="BRL" className="ddf-input" /></label><label>Estoque<input name="stock" type="number" min="0" step="1" className="ddf-input" /></label><label>Prazo em dias<input name="leadTimeDays" type="number" min="0" step="1" className="ddf-input" /></label><button className="ddf-button sm:col-span-2">Salvar oferta</button></form></details>; }
