'use client';
import{useCallback,useEffect,useState}from'react';
import{Bot,Box,CheckCircle2,KeyRound,Link2,LoaderCircle,Plus,RefreshCw,ShoppingBag,Store,TriangleAlert,X}from'lucide-react';
type Kind='SUPPLIER'|'CHANNEL'|'PROVIDER';
type Item={id:string;kind:Kind;providerKey:string;name:string;environment:string;status:string;secretFields:string[];lastTestedAt:string|null;lastError:string};
type Data={items:Item[];bindings:{id:string;brandName:string;storeName:string;integrationId:string|null;status:string}[];tests:unknown[]};
const presets=[
 {kind:'SUPPLIER',key:'generic-api',label:'Fornecedor via API',secrets:['apiKey','apiSecret'],config:['baseUrl','accountId'],capabilities:['catalog.read','cost.read','inventory.read','tracking.read']},
 {kind:'SUPPLIER',key:'feed',label:'Fornecedor via feed',secrets:['password'],config:['feedUrl','username'],capabilities:['catalog.read','cost.read','inventory.read']},
 {kind:'CHANNEL',key:'shopify',label:'Shopify',secrets:['accessToken'],config:['storeDomain'],capabilities:['listing.write','price.write','order.read','tracking.write']},
 {kind:'CHANNEL',key:'ebay',label:'eBay',secrets:['clientId','clientSecret','refreshToken'],config:['marketplace'],capabilities:['listing.write','order.read','tracking.write']},
 {kind:'CHANNEL',key:'amazon',label:'Amazon',secrets:['clientId','clientSecret','refreshToken'],config:['marketplaceId','sellerId'],capabilities:['listing.write','order.read','tracking.write']},
 {kind:'CHANNEL',key:'mercado-livre',label:'Mercado Livre',secrets:['clientId','clientSecret','refreshToken'],config:['sellerId'],capabilities:['listing.write','order.read','tracking.write']},
 {kind:'PROVIDER',key:'openai',label:'OpenAI',secrets:['apiKey'],config:['organizationId','projectId'],capabilities:['copy.generate','media.analyze']},
 {kind:'PROVIDER',key:'media',label:'Provedor de mídia',secrets:['apiKey'],config:['baseUrl'],capabilities:['image.generate','image.transform']},
] as const;
const labels:Record<string,string>={DRAFT:'Rascunho',CONFIGURED:'Configurado',TESTED:'Testado',ACTIVE:'Ativo',ERROR:'Com erro',DISABLED:'Desativado'};
export function ConnectorsWorkspace(){
 const[data,setData]=useState<Data>({items:[],bindings:[],tests:[]});const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[modal,setModal]=useState<Kind|'BINDING'|null>(null);const[presetKey,setPresetKey]=useState('');const[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/integrations',{cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error);setData(body);setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 function close(){setModal(null);setPresetKey('')}
 async function submit(form:FormData){setSaving(true);setError('');try{let payload:Record<string,unknown>;if(modal==='BINDING')payload={type:'binding',brandName:form.get('brandName'),storeName:form.get('storeName'),integrationId:form.get('integrationId')||null};else{const preset=presets.find(x=>x.kind===modal&&x.key===presetKey);if(!preset)throw new Error('Escolha uma integração.');payload={kind:preset.kind,providerKey:preset.key,name:form.get('name')||preset.label,environment:form.get('environment'),config:Object.fromEntries(preset.config.map(k=>[k,String(form.get(k)||'')]).filter(([,v])=>v)),secrets:Object.fromEntries(preset.secrets.map(k=>[k,String(form.get(k)||'')]).filter(([,v])=>v)),capabilities:preset.capabilities}}const r=await fetch('/api/integrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)throw new Error(body.error);close();await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSaving(false)}}
 async function test(id:string){setError('');const r=await fetch(`/api/integrations/${id}/test`,{method:'POST'});const body=await r.json();if(!r.ok)setError(body.error||body.message);await load()}
 async function toggle(item:Item){const target=item.status==='ACTIVE'?'DISABLED':'ACTIVE';if(target==='ACTIVE'&&!['TESTED','DISABLED'].includes(item.status)){setError('Teste a configuração antes de ativá-la.');return}const r=await fetch(`/api/integrations/${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:target})});const body=await r.json();if(!r.ok)setError(body.error);await load()}
 const count=(kind:Kind)=>data.items.filter(x=>x.kind===kind).length;
 return <div className="space-y-7">
  <header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="eyebrow">Sistema / fronteiras externas</p><h1 className="display-title">Central de Integrações</h1><p className="lede">Cadastre fornecedores, canais, provedores e destinos comerciais sem expor credenciais na interface.</p></div><button className="ddf-button flex items-center gap-2" onClick={()=>setModal('CHANNEL')}><Plus size={17}/>Nova integração</button></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[Box,'Fornecedores',count('SUPPLIER')],[ShoppingBag,'Canais',count('CHANNEL')],[Bot,'Provedores',count('PROVIDER')],[CheckCircle2,'Ativas',data.items.filter(x=>x.status==='ACTIVE').length]].map(([Icon,label,value])=>{const C=Icon as typeof Box;return <div className="surface flex items-center gap-4 p-5" key={String(label)}><span className="grid h-11 w-11 place-items-center rounded-lg bg-[#f0ece5]"><C size={20}/></span><div><p className="text-2xl font-bold">{String(value)}</p><p className="text-xs text-[#696d75]">{String(label)}</p></div></div>})}</section>
  <div className="surface flex items-start gap-3 border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><TriangleAlert className="mt-0.5 shrink-0" size={18}/><p><strong>Status real:</strong> salvar uma chave prepara o cofre. “Testado” valida a configuração disponível; a comunicação externa exige o adaptador específico do provedor.</p></div>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert">{error}</div>}
  <section><div className="section-heading"><div><h2>Conexões</h2><p>Credenciais criptografadas e nunca devolvidas ao navegador.</p></div><button className="ddf-button secondary flex items-center gap-2" onClick={()=>void load()}><RefreshCw size={15}/>Atualizar</button></div>
   {loading?<div className="surface grid min-h-48 place-items-center"><LoaderCircle className="animate-spin"/></div>:data.items.length===0?<div className="surface grid min-h-56 place-items-center p-8 text-center"><div><Link2 className="mx-auto mb-3 text-[#ff5b2e]"/><h3 className="font-semibold">Nenhuma conexão cadastrada</h3><p className="mt-1 text-sm text-[#696d75]">Comece pelo fornecedor ou canal usado primeiro.</p></div></div>:<div className="grid gap-4 lg:grid-cols-2">{data.items.map(item=><article className="surface p-5" key={item.id}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-widest text-[#696d75]">{item.kind} · {item.environment}</p><h3 className="mt-1 text-lg font-semibold">{item.name}</h3></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status==='ACTIVE'?'bg-green-100 text-green-800':item.status==='ERROR'?'bg-red-100 text-red-800':'bg-stone-200 text-stone-700'}`}>{labels[item.status]||item.status}</span></div><div className="mt-4 grid gap-2 text-sm"><p className="flex items-center gap-2"><KeyRound size={14}/>{item.secretFields.length} credencial(is) protegida(s)</p><p className="text-xs text-[#696d75]">Último teste: {item.lastTestedAt?new Date(item.lastTestedAt).toLocaleString('pt-BR'):'ainda não realizado'}</p>{item.lastError&&<p className="text-xs text-red-700">{item.lastError}</p>}</div><div className="mt-5 flex flex-wrap gap-2"><button className="ddf-button secondary" onClick={()=>void test(item.id)}>Testar configuração</button><button className="ddf-button" onClick={()=>void toggle(item)}>{item.status==='ACTIVE'?'Desativar':'Ativar'}</button></div></article>)}</div>}
  </section>
  <section><div className="section-heading"><div><h2>Marcas e lojas</h2><p>Vincule cada operação ao canal correspondente.</p></div><button className="ddf-button secondary flex items-center gap-2" onClick={()=>setModal('BINDING')}><Plus size={15}/>Adicionar destino</button></div><div className="surface overflow-hidden">{data.bindings.length===0?<p className="p-6 text-sm text-[#696d75]">Nenhuma marca ou loja vinculada.</p>:data.bindings.map(b=><div className="flex items-center gap-3 border-b border-[#ddd9d1] p-4 last:border-0" key={b.id}><Store size={18}/><div><p className="font-semibold">{b.brandName}</p><p className="text-xs text-[#696d75]">{b.storeName}</p></div></div>)}</div></section>
  {modal&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/50 p-4" role="dialog" aria-modal="true"><form className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-[#fbfaf7] p-6 shadow-2xl" action={submit}><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Configuração</p><h2 className="text-2xl font-bold">{modal==='BINDING'?'Nova marca ou loja':'Nova integração'}</h2></div><button type="button" onClick={close} aria-label="Fechar"><X/></button></div>
   {modal==='BINDING'?<div className="space-y-4"><Field label="Marca" name="brandName"/><Field label="Loja" name="storeName"/><label className="block text-sm font-semibold">Canal vinculado<select className="ddf-input" name="integrationId"><option value="">Vincular depois</option>{data.items.filter(x=>x.kind==='CHANNEL').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>:<div className="space-y-4"><div className="grid grid-cols-3 gap-2">{(['SUPPLIER','CHANNEL','PROVIDER']as Kind[]).map(k=><button type="button" className={`rounded-lg border p-3 text-xs font-bold ${modal===k?'border-[#ff5b2e] bg-[#ffe5dc]':'border-[#ddd9d1]'}`} onClick={()=>{setModal(k);setPresetKey('')}} key={k}>{k==='SUPPLIER'?'Fornecedor':k==='CHANNEL'?'Canal':'Mídia / IA'}</button>)}</div><label className="block text-sm font-semibold">Integração<select className="ddf-input" value={presetKey} onChange={e=>setPresetKey(e.target.value)} required><option value="">Selecione</option>{presets.filter(x=>x.kind===modal).map(x=><option value={x.key} key={x.key}>{x.label}</option>)}</select></label>{presetKey&&<IntegrationFields kind={modal} presetKey={presetKey}/>}</div>}
   <div className="mt-6 flex justify-end gap-3"><button type="button" className="ddf-button secondary" onClick={close}>Cancelar</button><button className="ddf-button" disabled={saving}>{saving?'Salvando…':'Salvar'}</button></div></form></div>}
 </div>
}
function Field({label,name,type='text'}:{label:string;name:string;type?:string}){return <label className="block text-sm font-semibold">{label}<input className="ddf-input" name={name} type={type} required/></label>}
function IntegrationFields({kind,presetKey}:{kind:Kind;presetKey:string}){const p=presets.find(x=>x.kind===kind&&x.key===presetKey);if(!p)return null;return <><label className="block text-sm font-semibold">Nome da conexão<input className="ddf-input" name="name" defaultValue={p.label} required/></label><label className="block text-sm font-semibold">Ambiente<select className="ddf-input" name="environment"><option value="PRODUCTION">Produção</option><option value="SANDBOX">Sandbox / teste</option></select></label>{p.config.map(f=><label className="block text-sm font-semibold" key={f}>{f}<input className="ddf-input" name={f}/></label>)}<div className="rounded-lg border border-[#ddd9d1] bg-white p-4"><p className="mb-3 flex items-center gap-2 text-sm font-bold"><KeyRound size={16}/>Credenciais protegidas</p>{p.secrets.map(f=><label className="mt-3 block text-sm font-semibold" key={f}>{f}<input className="ddf-input" type="password" name={f} autoComplete="new-password"/></label>)}</div></>}
