'use client';
/* eslint-disable @next/next/no-img-element -- URLs are user-controlled reviewed assets; optimization hosts are intentionally unknown. */
import { useEffect, useState } from 'react';
import Link from 'next/link';
import {useServerStates} from '@/components/use-server-states';
import {ProductListFilters,filterOptions} from '@/components/product-list-filters';
import {emptyProductFilters,matchesProductFilters,type ProductFilters} from '@/lib/product-filters';
import { studioReadiness, type MediaAsset, type MediaState } from '@/lib/media-factory';
import { command, errorMessage, sendCommand, type Command } from '@/lib/command-client';
import {  type ProductFactoryState } from '@/lib/product-factory';

const NAMESPACES = ['products', 'media', 'intake'] as const;
export function MediaFactoryWorkspace() {
  const {states,status,fromCache,error:loadError,reload}=useServerStates(NAMESPACES);
  const products=states.products; const media=states.media;
  const [filters,setFilters]=useState<ProductFilters>(emptyProductFilters); const [selected,setSelected]=useState<Set<string>>(new Set()); const [bulkBusy,setBulkBusy]=useState(false); const [queueStatus,setQueueStatus]=useState('');
  const updateFilters=(patch:Partial<ProductFilters>)=>{setFilters(current=>({...current,...patch}));setSelected(new Set());};
  const candidates=new Map(states.intake.candidates.map(candidate=>[candidate.id,candidate]));
  const visibleProducts=products.products.filter(product=>matchesProductFilters(product,candidates.get(product.candidateId),filters,studioReadiness(media,product.id).approvedCount)&&(!queueStatus||(media.productionRequests?.find(request=>request.productId===product.id)?.status??'SEM_SOLICITACAO')===queueStatus));
  const visibleIds=new Set(visibleProducts.map(product=>product.id));
  const filteredProducts={...products,products:visibleProducts};
  const selectedProducts=visibleProducts.filter(product=>selected.has(product.id));
  const allSelected=visibleProducts.length>0&&selectedProducts.length===visibleProducts.length;
  const selectedCommercial=media.assets.filter(asset=>selected.has(asset.productId)&&visibleIds.has(asset.productId)&&asset.kind==='DERIVADA'&&asset.status!=='REJEITADA');
  const reviewable=selectedCommercial.filter(asset=>asset.status==='EM_REVISAO');
  const archivable=selectedProducts.filter(product=>product.status==='EM_PRODUCAO'&&!product.archivedAt);
  async function approveSelected() {if(bulkBusy||!reviewable.length)return;setBulkBusy(true);setError('');let done=0;try{for(const asset of reviewable){await sendCommand(command('media.review',{assetId:asset.id,status:'APROVADA'}));done++;}setMessage(`${done} mídia(s) aprovada(s) após as validações de direitos e fidelidade.`);}catch(value){setError(`${done} mídia(s) já aprovada(s). ${errorMessage(value)}`);}finally{setBulkBusy(false);reload();}}
  async function removeSelected(archive:boolean) {const ids=archive?archivable.map(product=>product.id):selectedCommercial.map(asset=>asset.id);if(bulkBusy||!ids.length)return;const reason=window.prompt(archive?'Motivo para arquivar os produtos selecionados:':'Motivo para remover as mídias comerciais selecionadas:');if(!reason?.trim())return;if(!window.confirm(archive?`Arquivar ${ids.length} produto(s)? Os dados e originais serão preservados.`:`Retirar ${ids.length} mídia(s) do catálogo comercial? O histórico e os originais serão preservados.`))return;setBulkBusy(true);setError('');let done=0;try{for(let i=0;i<ids.length;i+=200){const batch=ids.slice(i,i+200);await sendCommand(command(archive?'products.bulkArchive':'media.bulkRemoveCommercialAssets',{[archive?'productIds':'assetIds']:batch,reason:reason.trim()}));done+=batch.length;}setMessage(`${done} ${archive?'produto(s) arquivado(s)':'mídia(s) retirada(s) do catálogo comercial'}.`);setSelected(new Set());}catch(value){setError(`${done} item(ns) concluído(s). ${errorMessage(value)}`);}finally{setBulkBusy(false);reload();}}

  const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
  async function bulk(type:'media.bulkSendToMedia'|'products.bulkRequestCompletion') {
    const ids=selectedProducts.filter(product=>product.status==='EM_PRODUCAO').map(product=>product.id); if(!ids.length||bulkBusy)return;
    setBulkBusy(true);setError('');let sent=0;
    try { for(let i=0;i<ids.length;i+=200){await sendCommand(command(type,{productIds:ids.slice(i,i+200)}));sent+=ids.slice(i,i+200).length;}setMessage(`${sent} produto(s) delegado(s) aos agentes. Pendências permanecem visíveis.`);setSelected(new Set()); }
    catch(value){setError(`${sent} produto(s) já enviado(s). ${errorMessage(value)}`);}finally{setBulkBusy(false);reload();}
  }
  const [error, setError] = useState(''); const [message, setMessage] = useState('');
  function act(cmd: Command, text: string) { sendCommand(cmd).then(() => { setError(''); setMessage(text); reload(); }, value => setError(errorMessage(value, 'Não foi possível salvar.'))); }
  const originals = media.assets.filter(asset => asset.kind === 'ORIGINAL');
  return <div className="space-y-6">
    <header><p className="eyebrow">Produção / ativos comerciais</p><h1 className="display-title">Media Factory</h1><p className="lede">Produção automática de fotos de estúdio a partir das referências preservadas do fornecedor.</p></header>
    <p className="surface p-4 text-sm">O catálogo recebe no mínimo quatro fotos de estúdio em ângulos distintos, com fundo neutro e fidelidade verificada. Originais ficam arquivados separadamente. Se faltarem referências ou geração configurada, o produto permanece bloqueado e o motivo aparece aqui.</p>
    {(error || loadError) && <p role="alert" className="border border-red-300 bg-red-50 p-4 text-red-800">{error || loadError}</p>}<p role="status" className="text-sm text-green-800">{message}</p>
    <ProductListFilters filters={filters} onChange={updateFilters} categories={filterOptions(products.products.map(product=>product.category))} suppliers={filterOptions(states.intake.candidates.map(candidate=>candidate.supplier?.name))}/>
    <section className="surface flex flex-wrap items-center gap-3 p-4"><label>Fila de mídia<select className="ddf-input" value={queueStatus} onChange={e=>{setQueueStatus(e.target.value);setSelected(new Set());}}><option value="">Todos os estados</option>{['SEM_SOLICITACAO','PENDENTE','PROCESSANDO','CONCLUIDO','BLOQUEADO','FALHOU'].map(value=><option key={value}>{value}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={allSelected} disabled={bulkBusy||!visibleProducts.length} onChange={()=>setSelected(allSelected?new Set():new Set(visibleProducts.map(product=>product.id)))}/>Selecionar todos no filtro ({visibleProducts.length})</label><span>{selectedProducts.length} selecionado(s)</span><button className="ddf-button" disabled={bulkBusy||!selectedProducts.some(product=>product.status==='EM_PRODUCAO')} onClick={()=>bulk('media.bulkSendToMedia')}>Produzir / tentar mídia novamente</button><button className="ddf-button secondary" disabled={bulkBusy||!selectedProducts.some(product=>product.status==='EM_PRODUCAO')} onClick={()=>bulk('products.bulkRequestCompletion')}>Delegar cadastro</button><button className="ddf-button" disabled={bulkBusy||!reviewable.length} onClick={approveSelected}>Aprovar mídias em revisão ({reviewable.length})</button><button className="ddf-button secondary" disabled={bulkBusy||!selectedCommercial.length} onClick={()=>removeSelected(false)}>Remover mídias comerciais ({selectedCommercial.length})</button><button className="ddf-button secondary" disabled={bulkBusy||!archivable.length} onClick={()=>removeSelected(true)}>Arquivar produtos ({archivable.length})</button><button className="ddf-button secondary" onClick={()=>{setFilters(emptyProductFilters);setQueueStatus('');setSelected(new Set());}}>Limpar filtros</button></section>
    {status!=='ready'&&!fromCache&&<p>Carregando produtos do servidor…</p>}
    <MediaDepartment products={filteredProducts} />
    <section className="surface p-5"><h2 className="text-xl font-semibold">Modelos reais para roupas</h2><p className="my-2 text-sm">Pastas individuais com fotos neutras, altura, peso e medidas do corpo para composições de vestuário com IA.</p><Link href="/modelos" className="ddf-button inline-block">Abrir catálogo de modelos</Link></section>
    <StudioProgress products={filteredProducts} media={media} selected={selected} onToggle={toggle} busy={bulkBusy} />
    <details className="surface p-4"><summary className="cursor-pointer font-semibold">Referências e ferramentas auxiliares</summary><div className="mt-4 space-y-4">
    {!loadError && <MediaUploadForm products={products} onStored={asset => act(command('media.addAsset', { asset }), 'Upload armazenado com direitos e checksum; aguardando revisão.')} />}
    {!loadError && <AssetReferenceForm products={products} originals={originals} onAdd={asset => act(command('media.addAsset', { asset }), 'Ativo versionado e enviado para revisão.')} />}
    {!loadError && <TransformationQueue state={{...media,jobs:media.jobs?.filter(job=>visibleIds.has(job.productId))}} onAct={act} />}
    </div></details>
    <AssetList assets={media.assets.filter(asset => asset.kind === 'DERIVADA'&&visibleIds.has(asset.productId))} title="Fotos comerciais de estúdio e derivados" products={products} onReview={(id,status) => act(command('media.review', { assetId: id, status }), status === 'APROVADA' ? 'Mídia aprovada.' : 'Mídia rejeitada e preservada no histórico.')} references={media.assets} />
    <details className="surface p-4"><summary className="cursor-pointer font-semibold">Arquivo de originais do fornecedor ({originals.length})</summary><div className="mt-4">
    <AssetList assets={originals.filter(asset=>visibleIds.has(asset.productId))} title="Originais preservados — fora do catálogo comercial" products={products} onReview={(id,status) => act(command('media.review', { assetId: id, status }), status === 'APROVADA' ? 'Mídia aprovada.' : 'Mídia rejeitada e preservada no histórico.')} />
    </div></details>
  </div>;
}

function StudioProgress({products,media,selected,onToggle,busy}:{products:ProductFactoryState;media:MediaState;selected:Set<string>;onToggle:(id:string)=>void;busy:boolean}) { return <section className="grid gap-3 md:grid-cols-3 xl:grid-cols-4">{products.products.map(product=>{const readiness=studioReadiness(media,product.id);const originals=media.assets.filter(asset=>asset.productId===product.id&&asset.kind==='ORIGINAL');return <article key={product.id} className="surface p-4 space-y-2"><label className="flex items-center gap-2"><input type="checkbox" checked={selected.has(product.id)} disabled={busy} onChange={()=>onToggle(product.id)} aria-label={`Selecionar ${product.universalTitle}`}/><h2 className="font-semibold">{product.universalTitle}</h2></label><p className="text-sm">{readiness.ready?'Estúdio concluído':'Aguardando produção de estúdio'} · {readiness.approvedCount}/{readiness.requiredCount} fotos</p><p className="text-xs text-gray-600">{originals.length} originais preservados</p>{media.productionRequests?.filter(request=>request.productId===product.id).map(request=><p key={request.id} className="text-xs">Fila: {request.status}{request.error?` · ${request.error}`:''}</p>)}{readiness.reasons.map(reason=><p key={reason} className="text-xs text-amber-800">{reason}</p>)}</article>})}{!products.products.length&&<p className="surface p-4 text-sm">Os produtos entram aqui automaticamente após a autorização de produção na Triagem.</p>}</section>; }

type DepartmentStatus = { gatewayStatus?: {configured:boolean;message:string}; studioStatus?: {available:boolean;message:string}; runs?: {candidateId:string;productId?:string;status:string;stage:string;detail?:{blocks?:string[];technicalGaps?:string[];studio?:{approvedCount:number;requiredCount:number}};attempts:number;updatedAt:string}[] };
function MediaDepartment({products}:{products:ProductFactoryState}) {
  const [status,setStatus]=useState<DepartmentStatus|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
  async function refresh() { const response=await fetch('/api/factory-production',{cache:'no-store'}); if(!response.ok) throw new Error('Não foi possível consultar o departamento de produção.'); setStatus(await response.json()); }
  useEffect(()=>{ let active=true; fetch('/api/factory-production',{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error('Estado da produção indisponível.');return response.json();}).then(value=>{if(active)setStatus(value);},value=>{if(active)setError(errorMessage(value,'Estado da produção indisponível.'));});return()=>{active=false;}; },[]);
  async function run() { setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/jobs/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tasks:['factoryProduction']})});const result=await response.json();await refresh();if(!response.ok)throw new Error(result.error||`Execução ${result.status??'indisponível'}; confira os bloqueios de produção.`);setNotice('Execução registrada. Produtos com referências ou capacidades insuficientes permanecem bloqueados.');}catch(value){setError(errorMessage(value,'Falha ao executar produção.'));}finally{setBusy(false);} }
  return <section className="surface p-5 space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Departamento de Estúdio</h2><p className="text-sm text-gray-600">Produção via IA central, após a autorização na Triagem.</p></div><button className="ddf-button" onClick={run} disabled={busy}>{busy?'Processando…':'Executar produção autorizada'}</button></div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[
      ['Análise das referências','Reúne todos os originais, a variante e a ficha técnica. Identifica ângulos comprovados e detalhes que precisam ser preservados.'],
      ['Geração de estúdio','No mínimo quatro imagens em fundo neutro, com ângulos distintos. O provedor deve aceitar fotografias de referência para edição fiel.'],
      ['Verificação automática','Confere forma, cor, material, textura e detalhes contra os originais. Nenhuma foto entra no catálogo sem evidência de fidelidade.'],
      ['Arquivo comercial','Guarda as fotos aprovadas para o cadastro. Originais continuam preservados em arquivo separado para reutilização.'],
    ].map(([title,text])=><article key={title} className="rounded border border-stone-200 p-3"><h3 className="font-semibold text-sm">{title}</h3><p className="mt-2 text-xs text-gray-600">{text}</p></article>)}</div>
    <p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">A conexão de IA central precisa oferecer edição com imagens de referência e análise visual de fidelidade. Geração apenas por texto não libera produtos para o catálogo.</p>
    {error&&<p role="alert" className="text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}
    {status&&<div className="space-y-3"><p className="text-sm"><strong>Conexão de IA:</strong> {status.gatewayStatus?.message??'Conexão configurada'}</p><p className="text-sm"><strong>Estúdio:</strong> {status.studioStatus?.message??'Estado não informado'}</p>{status.runs?.filter(run=>products.products.some(product=>product.id===run.productId)).map(run=><article key={run.candidateId} className="rounded border border-stone-200 p-3 text-sm"><h3 className="font-semibold">{products.products.find(product=>product.id===run.productId)?.universalTitle??'Produto em preparação'}</h3><p>{run.status==='BLOCKED'?'Produção bloqueada':run.status==='READY'?'Produção concluída':run.status==='FAILED'?'Falha na produção':run.status==='PROCESSING'?'Produção em andamento':'Aguardando processamento'}</p>{run.detail?.studio&&<p>Estúdio: {run.detail.studio.approvedCount}/{run.detail.studio.requiredCount} fotos aprovadas</p>}{[...(run.detail?.blocks??[]),...(run.detail?.technicalGaps??[])].map((reason,index)=><p key={index} className="mt-1 text-amber-900">{reason}</p>)}</article>)}</div>}
  </section>;
}

function RightsFields() { return <><label>Direitos de uso<select name="rightsStatus" className="ddf-input" defaultValue="DECLARADO"><option value="DECLARADO">Declarado pelo responsável</option><option value="LICENCIADO">Licenciado</option><option value="DESCONHECIDO">Desconhecido — bloqueia aprovação</option><option value="EXPIRADO">Expirado — bloqueia aprovação</option></select></label><label>Titular dos direitos<input name="rightsHolder" className="ddf-input" placeholder="Fornecedor, marca ou fotógrafo" /></label><label>Validade dos direitos<input type="date" name="rightsExpiresAt" className="ddf-input" /></label></>; }
function ProductSelect({products}:{products:ProductFactoryState}) { return <label>Produto mestre<select required name="productId" className="ddf-input"><option value="">Selecione</option>{products.products.filter(product => product.status === 'EM_PRODUCAO').map(product => <option key={product.id} value={product.id}>{product.universalTitle}</option>)}</select></label>; }

function AssetReferenceForm({products,originals,onAdd}:{products:ProductFactoryState; originals:MediaAsset[]; onAdd:(asset:Omit<MediaAsset,'id'|'status'|'createdAt'>)=>void}) {
  const [kind,setKind] = useState<'ORIGINAL'|'DERIVADA'>('ORIGINAL');
  return <form className="surface grid gap-4 p-6 md:grid-cols-2" onSubmit={event => { event.preventDefault(); const form=event.currentTarget; const d=new FormData(form); onAdd({ productId:String(d.get('productId')),url:String(d.get('url')),kind,purpose:String(d.get('purpose')),provenance:String(d.get('provenance')),originalAssetId:kind==='DERIVADA'?String(d.get('originalAssetId')):undefined,destination:String(d.get('destination')),format:String(d.get('format')) as MediaAsset['format'],aspectRatio:String(d.get('aspectRatio')) as MediaAsset['aspectRatio'],rightsStatus:String(d.get('rightsStatus')) as MediaAsset['rightsStatus'],rightsHolder:String(d.get('rightsHolder')),rightsExpiresAt:String(d.get('rightsExpiresAt'))||undefined,transformationNotes:kind==='DERIVADA'?String(d.get('transformationNotes')):undefined,changesProductAppearance:d.get('changesProductAppearance')==='on' }); form.reset(); setKind('ORIGINAL'); }}>
    <h2 className="text-xl font-semibold md:col-span-2">Registrar referência externa</h2><ProductSelect products={products}/><label>URL do arquivo<input required type="url" name="url" className="ddf-input" placeholder="https://" /></label>
    <label>Tipo<select name="kind" className="ddf-input" value={kind} onChange={e=>setKind(e.target.value as 'ORIGINAL'|'DERIVADA')}><option value="ORIGINAL">Original</option><option value="DERIVADA">Derivada</option></select></label>
    {kind==='DERIVADA'&&<><label>Original de referência<select required name="originalAssetId" className="ddf-input"><option value="">Selecione</option>{originals.map(asset=><option key={asset.id} value={asset.id}>{asset.purpose} · v{asset.version??1}</option>)}</select></label><label>Transformações realizadas<input required name="transformationNotes" className="ddf-input" placeholder="Corte e conversão, sem alterar o produto" /></label><label className="flex items-center gap-2"><input type="checkbox" name="changesProductAppearance"/> A transformação altera cor, forma, material, escala ou detalhes do produto</label></>}
    <label>Finalidade<input required name="purpose" className="ddf-input" /></label><label>Proveniência<input required name="provenance" className="ddf-input" /></label>
    <label>Destino<input name="destination" className="ddf-input" defaultValue="Universal" /></label><label>Formato<select name="format" className="ddf-input"><option>ORIGINAL</option><option>JPEG</option><option>PNG</option><option>WEBP</option><option>AVIF</option><option>MP4</option><option>WEBM</option></select></label><label>Proporção<select name="aspectRatio" className="ddf-input"><option>ORIGINAL</option><option>1:1</option><option>4:5</option><option>9:16</option><option>16:9</option></select></label><RightsFields/><button className="ddf-button md:col-span-2">Enviar para revisão</button>
  </form>;
}

function TransformationQueue({state,onAct}:{state:MediaState;onAct:(cmd:Command,text:string)=>void}) {
  const approved=state.assets.filter(asset=>asset.kind==='ORIGINAL'&&asset.status==='APROVADA');
  return <section className="surface space-y-4 p-6"><h2 className="text-xl font-semibold">Fila de transformação</h2><form className="grid gap-3 md:grid-cols-3" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const d=new FormData(form);onAct(command('media.enqueueTransformation',{sourceAssetId:String(d.get('sourceAssetId')),kind:String(d.get('kind')),destination:String(d.get('destination')),format:String(d.get('format')),aspectRatio:String(d.get('aspectRatio'))}),'Job adicionado à fila controlada.');form.reset()}}><label>Original aprovado<select required name="sourceAssetId" className="ddf-input"><option value="">Selecione</option>{approved.map(a=><option key={a.id} value={a.id}>{a.purpose} · v{a.version??1}</option>)}</select></label><label>Operação<select name="kind" className="ddf-input"><option>REDIMENSIONAR</option><option>REENQUADRAR</option><option>CONVERTER</option><option>OTIMIZAR</option></select></label><label>Destino<input required name="destination" className="ddf-input" placeholder="Instagram, loja…"/></label><label>Formato<select name="format" className="ddf-input"><option>WEBP</option><option>JPEG</option><option>PNG</option><option>AVIF</option><option>MP4</option><option>WEBM</option></select></label><label>Proporção<select name="aspectRatio" className="ddf-input"><option>1:1</option><option>4:5</option><option>9:16</option><option>16:9</option><option>ORIGINAL</option></select></label><button className="ddf-button self-end">Criar job</button></form>
    <div className="space-y-2">{(state.jobs??[]).length===0&&<p className="text-sm text-gray-600">Nenhum job na fila.</p>}{(state.jobs??[]).map(job=><article key={job.id} className="rounded border border-stone-200 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{job.kind} · {job.destination} · {job.format} {job.aspectRatio}</strong><span>{job.status}</span></div>{job.error&&<p className="text-red-800">{job.error}</p>}{job.status==='PENDENTE'&&<button className="ddf-button secondary mt-2" onClick={()=>onAct(command('media.updateJob',{jobId:job.id,status:'PROCESSANDO'}),'Job em processamento controlado.')}>Iniciar processamento</button>}{job.status==='PROCESSANDO'&&<JobCompletion jobId={job.id} onAct={onAct}/>}</article>)}</div>
  </section>;
}

function JobCompletion({jobId,onAct}:{jobId:string;onAct:(cmd:Command,text:string)=>void}) { return <form className="mt-3 grid gap-2 md:grid-cols-2" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const d=new FormData(form);onAct(command('media.completeTransformation',{jobId,derived:{url:String(d.get('url')),purpose:String(d.get('purpose')),provenance:String(d.get('provenance')),rightsHolder:String(d.get('rightsHolder')),transformationNotes:String(d.get('notes')),changesProductAppearance:d.get('misleading')==='on'}}),'Job concluído; derivada enviada à revisão.');form.reset()}}><input required type="url" name="url" className="ddf-input" placeholder="URL da saída processada"/><input required name="purpose" className="ddf-input" placeholder="Finalidade"/><input required name="provenance" className="ddf-input" placeholder="Processador e proveniência"/><input name="rightsHolder" className="ddf-input" placeholder="Titular"/><input required name="notes" className="ddf-input" placeholder="Transformações realizadas"/><label className="flex items-center gap-2"><input type="checkbox" name="misleading"/> Alterou aparência do produto</label><button className="ddf-button">Concluir e revisar</button><button type="button" className="ddf-button secondary" onClick={()=>onAct(command('media.updateJob',{jobId,status:'FALHOU',error:'Processamento reportado como falho.'}),'Falha registrada para recuperação.')}>Registrar falha</button></form>; }

function AssetList({assets,products,onReview,title='Ativos e comparação',references=assets}:{assets:MediaAsset[];products:ProductFactoryState;title?:string;references?:MediaAsset[];onReview:(id:string,status:'APROVADA'|'REJEITADA')=>void}) { return <section className="space-y-3"><h2 className="text-xl font-semibold">{title}</h2>{assets.length===0&&<p className="surface p-8">Nenhuma mídia registrada.</p>}{assets.map(asset=>{const product=products.products.find(p=>p.id===asset.productId);const original=references.find(a=>a.id===asset.originalAssetId);return <article className="surface space-y-3 p-5" key={asset.id}><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{product?.universalTitle??'Produto não encontrado'} · {asset.purpose} · v{asset.version??1}</h3><span className="rounded bg-stone-200 px-3 py-1 text-sm">{asset.status.replace('_',' ')}</span></div>{original?<div className="grid gap-3 md:grid-cols-2"><MediaPreview asset={original} label="Original"/><MediaPreview asset={asset} label="Derivada"/></div>:<MediaPreview asset={asset} label="Original"/>}<p>{asset.studio?'Estúdio comercial':asset.kind} · {asset.studioAngle??''} · {asset.destination??'Universal'} · {asset.format??'ORIGINAL'} · {asset.aspectRatio??'ORIGINAL'}</p><p className="text-sm text-gray-600">Origem: {asset.provenance} · Direitos: {asset.rightsStatus??'DECLARADO'}{asset.rightsHolder?` — ${asset.rightsHolder}`:''}</p>{asset.transformationNotes&&<p className="text-sm">Transformação: {asset.transformationNotes}</p>}{asset.changesProductAppearance&&<p role="alert" className="border border-red-300 bg-red-50 p-3 text-red-800">Guardrail: possível alteração enganosa; aprovação bloqueada.</p>}{asset.status==='EM_REVISAO'&&<div className="flex gap-3"><button className="ddf-button" onClick={()=>onReview(asset.id,'APROVADA')}>Aprovar mídia</button><button className="ddf-button secondary" onClick={()=>onReview(asset.id,'REJEITADA')}>Rejeitar</button></div>}</article>})}</section>; }
function MediaPreview({asset,label}:{asset:MediaAsset;label:string}) { const video=asset.mimeType?.startsWith('video/')||/\.(mp4|webm)(\?|$)/i.test(asset.url);return <figure className="rounded border border-stone-200 p-2"><figcaption className="mb-2 text-sm font-semibold">{label}</figcaption>{video?<video className="max-h-52 w-full object-contain" controls src={asset.url}/>:<img className="max-h-52 w-full object-contain" src={asset.url} alt={`${label}: ${asset.purpose}`}/>}</figure>; }

function MediaUploadForm({products,onStored}:{products:ProductFactoryState;onStored:(asset:Omit<MediaAsset,'id'|'status'|'createdAt'>)=>void}) {
 const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 return <form className="surface grid gap-4 p-6 md:grid-cols-2" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);const upload=new FormData();upload.set('file',data.get('file')!);try{const response=await fetch('/api/media',{method:'POST',body:upload});const result=await response.json();if(!response.ok)throw new Error(result.error||'Upload falhou.');onStored({productId:String(data.get('productId')),url:result.url,kind:'ORIGINAL',purpose:String(data.get('purpose')),provenance:String(data.get('provenance')),checksum:result.checksum,mimeType:result.mimeType,bytes:result.bytes,rightsStatus:String(data.get('rightsStatus')) as MediaAsset['rightsStatus'],rightsHolder:String(data.get('rightsHolder')),rightsExpiresAt:String(data.get('rightsExpiresAt'))||undefined,destination:'Universal',format:'ORIGINAL',aspectRatio:'ORIGINAL'});form.reset()}catch(value){setError(value instanceof Error?value.message:'Upload falhou.')}finally{setBusy(false)}}}><h2 className="text-xl font-semibold md:col-span-2">Upload seguro de original</h2>{error&&<p role="alert" className="text-red-800 md:col-span-2">{error}</p>}<ProductSelect products={products}/><label>Arquivo — imagem ou vídeo até 10 MB<input required type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" className="ddf-input" /></label><label>Finalidade<input required name="purpose" className="ddf-input" /></label><label>Proveniência<input required name="provenance" className="ddf-input" /></label><RightsFields/><button className="ddf-button md:col-span-2" disabled={busy}>{busy?'Enviando…':'Armazenar e revisar'}</button></form>;
}
