'use client';
import { useState, useSyncExternalStore } from 'react';
import { addMedia, emptyMedia, MEDIA_STORAGE_KEY, reviewMedia, type MediaState } from '@/lib/media-factory';
import { emptyProductFactory, PRODUCT_STORAGE_KEY, type ProductFactoryState } from '@/lib/product-factory';
const eventName = 'ddf-media-change';
function subscribe(cb: () => void) { window.addEventListener('storage', cb); window.addEventListener(eventName, cb); return () => { window.removeEventListener('storage', cb); window.removeEventListener(eventName, cb); }; }
function snapshot() { try { return `${localStorage.getItem(PRODUCT_STORAGE_KEY) ?? ''}\n${localStorage.getItem(MEDIA_STORAGE_KEY) ?? ''}`; } catch { return 'unavailable'; } }
export function MediaFactoryWorkspace() {
  const raw = useSyncExternalStore(subscribe, snapshot, () => null); let products: ProductFactoryState = emptyProductFactory; let media: MediaState = emptyMedia; let loadError = '';
  try { if (raw) { const [p, m] = raw.split('\n'); products = p ? JSON.parse(p) : emptyProductFactory; media = m ? JSON.parse(m) : emptyMedia; if (!Array.isArray(products.products) || !Array.isArray(media.assets)) throw new Error(); } } catch { loadError = 'Dados locais inválidos; edição bloqueada.'; }
  const [error, setError] = useState(''); const [message, setMessage] = useState('');
  function save(next: MediaState) { if (snapshot() !== raw) throw new Error('Os dados mudaram em outra aba. Revise antes de repetir.'); localStorage.setItem(MEDIA_STORAGE_KEY, JSON.stringify(next)); window.dispatchEvent(new Event(eventName)); setError(''); }
  function act(fn: () => MediaState, messageText: string) { try { save(fn()); setMessage(messageText); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível salvar.'); } }
  return <div className="space-y-6"><header><p className="eyebrow">Produção / ativos comerciais</p><h1 className="display-title">Media Factory</h1><p className="lede">Registre origem, finalidade e revisão sem confundir mídia original com derivada.</p></header><p className="surface p-4 text-sm">Upload seguro de imagens e vídeos ou referência externa por URL. Nenhuma mídia é transformada sem aprovação.</p>{(error || loadError) && <p role="alert" className="border border-red-300 bg-red-50 p-4 text-red-800">{error || loadError}</p>}<p role="status" className="text-sm text-green-800">{message}</p>
  {!loadError && <MediaUploadForm products={products} onStored={asset=>act(()=>addMedia(media,asset,crypto.randomUUID(),new Date().toISOString()),'Upload armazenado com checksum e enviado para revisão.')} />}
  {!loadError && <form className="surface grid gap-4 p-6" onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const d = new FormData(form); const productId = String(d.get('productId')); act(() => addMedia(media, { productId, url: String(d.get('url')), kind: String(d.get('kind')) as 'ORIGINAL'|'DERIVADA', purpose: String(d.get('purpose')), provenance: String(d.get('provenance')) }, crypto.randomUUID(), new Date().toISOString()), 'Mídia registrada para revisão.'); form.reset(); }}><h2 className="text-xl font-semibold">Adicionar ativo</h2><label>Produto mestre<select required name="productId" className="ddf-input"><option value="">Selecione</option>{products.products.filter(p => p.status === 'EM_PRODUCAO').map(p => <option key={p.id} value={p.id}>{p.universalTitle}</option>)}</select></label><label>URL do arquivo<input required type="url" name="url" className="ddf-input" placeholder="https://" /></label><label>Tipo<select name="kind" className="ddf-input"><option value="ORIGINAL">Original</option><option value="DERIVADA">Derivada</option></select></label><label>Finalidade<input required name="purpose" className="ddf-input" placeholder="Imagem principal, galeria, demonstração…" /></label><label>Proveniência<input required name="provenance" className="ddf-input" placeholder="Fonte e direitos conhecidos" /></label><button className="ddf-button">Enviar para revisão</button></form>}
  <section className="space-y-3">{media.assets.length === 0 && <p className="surface p-8">Nenhuma mídia registrada.</p>}{media.assets.map(a => { const product = products.products.find(p => p.id === a.productId); return <article className="surface space-y-3 p-5" key={a.id}><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold">{product?.universalTitle ?? 'Produto não encontrado'}</h2><span className="rounded bg-stone-200 px-3 py-1 text-sm">{a.status.replace('_', ' ')}</span></div><p className="break-all text-sm">{a.url}</p><p>{a.kind} · {a.purpose}</p><p className="text-sm text-gray-600">Origem: {a.provenance}</p>{a.status === 'EM_REVISAO' && <div className="flex gap-3"><button className="ddf-button" onClick={() => act(() => reviewMedia(media, a.id, 'APROVADA'), 'Mídia aprovada.')}>Aprovar mídia</button><button className="ddf-button secondary" onClick={() => act(() => reviewMedia(media, a.id, 'REJEITADA'), 'Mídia rejeitada e preservada no histórico local.')}>Rejeitar</button></div>}</article>; })}</section></div>;
}

function MediaUploadForm({products,onStored}:{products:ProductFactoryState;onStored:(asset:{productId:string;url:string;kind:'ORIGINAL'|'DERIVADA';purpose:string;provenance:string;checksum?:string;mimeType?:string;bytes?:number})=>void}){
 const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 return <form className="surface grid gap-4 p-6" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);const upload=new FormData();upload.set('file',data.get('file')!);try{const response=await fetch('/api/media',{method:'POST',body:upload});const result=await response.json();if(!response.ok)throw new Error(result.error||'Upload falhou.');onStored({productId:String(data.get('productId')),url:result.url,kind:String(data.get('kind')) as 'ORIGINAL'|'DERIVADA',purpose:String(data.get('purpose')),provenance:String(data.get('provenance')),checksum:result.checksum,mimeType:result.mimeType,bytes:result.bytes});form.reset()}catch(value){setError(value instanceof Error?value.message:'Upload falhou.')}finally{setBusy(false)}}}>
  <h2 className="text-xl font-semibold">Upload seguro</h2>{error&&<p role="alert" className="text-red-800">{error}</p>}
  <label>Produto mestre<select required name="productId" className="ddf-input"><option value="">Selecione</option>{products.products.filter(product=>product.status==='EM_PRODUCAO').map(product=><option key={product.id} value={product.id}>{product.universalTitle}</option>)}</select></label>
  <label>Arquivo — imagem ou vídeo até 10 MB<input required type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" className="ddf-input" /></label>
  <label>Tipo<select name="kind" className="ddf-input"><option value="ORIGINAL">Original</option><option value="DERIVADA">Derivada</option></select></label>
  <label>Finalidade<input required name="purpose" className="ddf-input" /></label><label>Proveniência e direitos<input required name="provenance" className="ddf-input" /></label>
  <button className="ddf-button" disabled={busy}>{busy?'Enviando…':'Armazenar e revisar'}</button>
 </form>
}
