'use client';
/* eslint-disable @next/next/no-img-element -- URLs are user-controlled reviewed assets; optimization hosts are intentionally unknown. */
import { useState, useSyncExternalStore } from 'react';
import { addMedia, completeTransformation, emptyMedia, enqueueTransformation, MEDIA_STORAGE_KEY, reviewMedia, updateTransformationJob, type MediaAsset, type MediaState } from '@/lib/media-factory';
import { emptyProductFactory, PRODUCT_STORAGE_KEY, type ProductFactoryState } from '@/lib/product-factory';

const eventName = 'ddf-media-change';
function subscribe(cb: () => void) { window.addEventListener('storage', cb); window.addEventListener(eventName, cb); return () => { window.removeEventListener('storage', cb); window.removeEventListener(eventName, cb); }; }
function snapshot() { try { return `${localStorage.getItem(PRODUCT_STORAGE_KEY) ?? ''}\n${localStorage.getItem(MEDIA_STORAGE_KEY) ?? ''}`; } catch { return 'unavailable'; } }
const now = () => new Date().toISOString();

export function MediaFactoryWorkspace() {
  const raw = useSyncExternalStore(subscribe, snapshot, () => null);
  let products: ProductFactoryState = emptyProductFactory; let media: MediaState = emptyMedia; let loadError = '';
  try { if (raw) { const [p, m] = raw.split('\n'); products = p ? JSON.parse(p) : emptyProductFactory; media = m ? JSON.parse(m) : emptyMedia; if (!Array.isArray(products.products) || !Array.isArray(media.assets)) throw new Error(); } } catch { loadError = 'Dados locais inválidos; edição bloqueada.'; }
  const [error, setError] = useState(''); const [message, setMessage] = useState('');
  function save(next: MediaState) { if (snapshot() !== raw) throw new Error('Os dados mudaram em outra aba. Revise antes de repetir.'); localStorage.setItem(MEDIA_STORAGE_KEY, JSON.stringify(next)); window.dispatchEvent(new Event(eventName)); setError(''); }
  function act(fn: () => MediaState, text: string) { try { save(fn()); setMessage(text); } catch (value) { setError(value instanceof Error ? value.message : 'Não foi possível salvar.'); } }
  const originals = media.assets.filter(asset => asset.kind === 'ORIGINAL');
  return <div className="space-y-6">
    <header><p className="eyebrow">Produção / ativos comerciais</p><h1 className="display-title">Media Factory</h1><p className="lede">Versões, direitos, destinos e transformações rastreáveis do original à derivada.</p></header>
    <p className="surface p-4 text-sm">Toda derivada aponta para um original aprovado. Alterações capazes de distorcer a aparência do produto são bloqueadas.</p>
    {(error || loadError) && <p role="alert" className="border border-red-300 bg-red-50 p-4 text-red-800">{error || loadError}</p>}<p role="status" className="text-sm text-green-800">{message}</p>
    {!loadError && <MediaUploadForm products={products} onStored={asset => act(() => addMedia(media, asset, crypto.randomUUID(), now()), 'Upload armazenado com direitos e checksum; aguardando revisão.')} />}
    {!loadError && <AssetReferenceForm products={products} originals={originals} onAdd={asset => act(() => addMedia(media, asset, crypto.randomUUID(), now()), 'Ativo versionado e enviado para revisão.')} />}
    {!loadError && <TransformationQueue state={media} onAct={act} />}
    <AssetList assets={media.assets} products={products} onReview={(id,status) => act(() => reviewMedia(media,id,status), status === 'APROVADA' ? 'Mídia aprovada.' : 'Mídia rejeitada e preservada no histórico.')} />
  </div>;
}

function RightsFields() { return <><label>Direitos de uso<select name="rightsStatus" className="ddf-input" defaultValue="DECLARADO"><option value="DECLARADO">Declarado pelo responsável</option><option value="LICENCIADO">Licenciado</option><option value="DESCONHECIDO">Desconhecido — bloqueia aprovação</option><option value="EXPIRADO">Expirado — bloqueia aprovação</option></select></label><label>Titular dos direitos<input name="rightsHolder" className="ddf-input" placeholder="Fornecedor, marca ou fotógrafo" /></label><label>Validade dos direitos<input type="date" name="rightsExpiresAt" className="ddf-input" /></label></>; }
function ProductSelect({products}:{products:ProductFactoryState}) { return <label>Produto mestre<select required name="productId" className="ddf-input"><option value="">Selecione</option>{products.products.filter(product => product.status === 'EM_PRODUCAO').map(product => <option key={product.id} value={product.id}>{product.universalTitle}</option>)}</select></label>; }

function AssetReferenceForm({products,originals,onAdd}:{products:ProductFactoryState; originals:MediaAsset[]; onAdd:(asset:Omit<MediaAsset,'id'|'status'|'createdAt'>)=>void}) {
  const [kind,setKind] = useState<'ORIGINAL'|'DERIVADA'>('ORIGINAL');
  return <form className="surface grid gap-4 p-6 md:grid-cols-2" onSubmit={event => { event.preventDefault(); const form=event.currentTarget; const d=new FormData(form); onAdd({ productId:String(d.get('productId')),url:String(d.get('url')),kind,purpose:String(d.get('purpose')),provenance:String(d.get('provenance')),originalAssetId:kind==='DERIVADA'?String(d.get('originalAssetId')):undefined,destination:String(d.get('destination')),format:String(d.get('format')) as MediaAsset['format'],aspectRatio:String(d.get('aspectRatio')) as MediaAsset['aspectRatio'],rightsStatus:String(d.get('rightsStatus')) as MediaAsset['rightsStatus'],rightsHolder:String(d.get('rightsHolder')),rightsExpiresAt:String(d.get('rightsExpiresAt'))||undefined,transformationNotes:kind==='DERIVADA'?String(d.get('transformationNotes')):undefined,changesProductAppearance:d.get('changesProductAppearance')==='on' }); form.reset(); setKind('ORIGINAL'); }}>
    <h2 className="text-xl font-semibold md:col-span-2">Registrar referência externa</h2><ProductSelect products={products}/><label>URL do arquivo<input required type="url" name="url" className="ddf-input" placeholder="https://" /></label>
    <label>Tipo<select name="kind" className="ddf-input" value={kind} onChange={e=>setKind(e.target.value as 'ORIGINAL'|'DERIVADA')}><option value="ORIGINAL">Original</option><option value="DERIVADA">Derivada</option></select></label>
    {kind==='DERIVADA'&&<><label>Original de referência<select required name="originalAssetId" className="ddf-input"><option value="">Selecione</option>{originals.map(asset=><option key={asset.id} value={asset.id}>{asset.purpose} · v{asset.version??1}</option>)}</select></label><label>Transformações realizadas<input required name="transformationNotes" className="ddf-input" placeholder="Corte e conversão, sem alterar o produto" /></label><label className="flex items-center gap-2"><input type="checkbox" name="changesProductAppearance"/> A transformação altera cor, forma, material, escala ou detalhes do produto</label></>}
    <label>Finalidade<input required name="purpose" className="ddf-input" /></label><label>Proveniência<input required name="provenance" className="ddf-input" /></label>
    <label>Destino<input name="destination" className="ddf-input" defaultValue="Universal" /></label><label>Formato<select name="format" className="ddf-input"><option>ORIGINAL</option><option>JPEG</option><option>PNG</option><option>WEBP</option><option>AVIF</option><option>MP4</option><option>WEBM</option></select></label><label>Proporção<select name="aspectRatio" className="ddf-input"><option>ORIGINAL</option><option>1:1</option><option>4:5</option><option>9:16</option><option>16:9</option></select></label><RightsFields/><button className="ddf-button md:col-span-2">Enviar para revisão</button>
  </form>;
}

function TransformationQueue({state,onAct}:{state:MediaState;onAct:(fn:()=>MediaState,text:string)=>void}) {
  const approved=state.assets.filter(asset=>asset.kind==='ORIGINAL'&&asset.status==='APROVADA');
  return <section className="surface space-y-4 p-6"><h2 className="text-xl font-semibold">Fila de transformação</h2><form className="grid gap-3 md:grid-cols-3" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const d=new FormData(form);const source=state.assets.find(a=>a.id===String(d.get('sourceAssetId')))!;onAct(()=>enqueueTransformation(state,{id:crypto.randomUUID(),productId:source.productId,sourceAssetId:source.id,kind:String(d.get('kind')) as 'REDIMENSIONAR',destination:String(d.get('destination')),format:String(d.get('format')) as 'WEBP',aspectRatio:String(d.get('aspectRatio')) as '1:1'},now()),'Job adicionado à fila controlada.');form.reset()}}><label>Original aprovado<select required name="sourceAssetId" className="ddf-input"><option value="">Selecione</option>{approved.map(a=><option key={a.id} value={a.id}>{a.purpose} · v{a.version??1}</option>)}</select></label><label>Operação<select name="kind" className="ddf-input"><option>REDIMENSIONAR</option><option>REENQUADRAR</option><option>CONVERTER</option><option>OTIMIZAR</option></select></label><label>Destino<input required name="destination" className="ddf-input" placeholder="Instagram, loja…"/></label><label>Formato<select name="format" className="ddf-input"><option>WEBP</option><option>JPEG</option><option>PNG</option><option>AVIF</option><option>MP4</option><option>WEBM</option></select></label><label>Proporção<select name="aspectRatio" className="ddf-input"><option>1:1</option><option>4:5</option><option>9:16</option><option>16:9</option><option>ORIGINAL</option></select></label><button className="ddf-button self-end">Criar job</button></form>
    <div className="space-y-2">{(state.jobs??[]).length===0&&<p className="text-sm text-gray-600">Nenhum job na fila.</p>}{(state.jobs??[]).map(job=><article key={job.id} className="rounded border border-stone-200 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{job.kind} · {job.destination} · {job.format} {job.aspectRatio}</strong><span>{job.status}</span></div>{job.error&&<p className="text-red-800">{job.error}</p>}{job.status==='PENDENTE'&&<button className="ddf-button secondary mt-2" onClick={()=>onAct(()=>updateTransformationJob(state,job.id,'PROCESSANDO',now()),'Job em processamento controlado.')}>Iniciar processamento</button>}{job.status==='PROCESSANDO'&&<JobCompletion jobId={job.id} state={state} onAct={onAct}/>}</article>)}</div>
  </section>;
}

function JobCompletion({jobId,state,onAct}:{jobId:string;state:MediaState;onAct:(fn:()=>MediaState,text:string)=>void}) { return <form className="mt-3 grid gap-2 md:grid-cols-2" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const d=new FormData(form);onAct(()=>completeTransformation(state,jobId,{url:String(d.get('url')),purpose:String(d.get('purpose')),provenance:String(d.get('provenance')),rightsStatus:'DECLARADO',rightsHolder:String(d.get('rightsHolder')),transformationNotes:String(d.get('notes')),changesProductAppearance:d.get('misleading')==='on'},crypto.randomUUID(),now()),'Job concluído; derivada enviada à revisão.');form.reset()}}><input required type="url" name="url" className="ddf-input" placeholder="URL da saída processada"/><input required name="purpose" className="ddf-input" placeholder="Finalidade"/><input required name="provenance" className="ddf-input" placeholder="Processador e proveniência"/><input name="rightsHolder" className="ddf-input" placeholder="Titular"/><input required name="notes" className="ddf-input" placeholder="Transformações realizadas"/><label className="flex items-center gap-2"><input type="checkbox" name="misleading"/> Alterou aparência do produto</label><button className="ddf-button">Concluir e revisar</button><button type="button" className="ddf-button secondary" onClick={()=>onAct(()=>updateTransformationJob(state,jobId,'FALHOU',now(),'Processamento reportado como falho.'),'Falha registrada para recuperação.')}>Registrar falha</button></form>; }

function AssetList({assets,products,onReview}:{assets:MediaAsset[];products:ProductFactoryState;onReview:(id:string,status:'APROVADA'|'REJEITADA')=>void}) { return <section className="space-y-3"><h2 className="text-xl font-semibold">Ativos e comparação</h2>{assets.length===0&&<p className="surface p-8">Nenhuma mídia registrada.</p>}{assets.map(asset=>{const product=products.products.find(p=>p.id===asset.productId);const original=assets.find(a=>a.id===asset.originalAssetId);return <article className="surface space-y-3 p-5" key={asset.id}><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{product?.universalTitle??'Produto não encontrado'} · {asset.purpose} · v{asset.version??1}</h3><span className="rounded bg-stone-200 px-3 py-1 text-sm">{asset.status.replace('_',' ')}</span></div>{original?<div className="grid gap-3 md:grid-cols-2"><MediaPreview asset={original} label="Original"/><MediaPreview asset={asset} label="Derivada"/></div>:<MediaPreview asset={asset} label="Original"/>}<p>{asset.kind} · {asset.destination??'Universal'} · {asset.format??'ORIGINAL'} · {asset.aspectRatio??'ORIGINAL'}</p><p className="text-sm text-gray-600">Origem: {asset.provenance} · Direitos: {asset.rightsStatus??'DECLARADO'}{asset.rightsHolder?` — ${asset.rightsHolder}`:''}</p>{asset.transformationNotes&&<p className="text-sm">Transformação: {asset.transformationNotes}</p>}{asset.changesProductAppearance&&<p role="alert" className="border border-red-300 bg-red-50 p-3 text-red-800">Guardrail: possível alteração enganosa; aprovação bloqueada.</p>}{asset.status==='EM_REVISAO'&&<div className="flex gap-3"><button className="ddf-button" onClick={()=>onReview(asset.id,'APROVADA')}>Aprovar mídia</button><button className="ddf-button secondary" onClick={()=>onReview(asset.id,'REJEITADA')}>Rejeitar</button></div>}</article>})}</section>; }
function MediaPreview({asset,label}:{asset:MediaAsset;label:string}) { const video=asset.mimeType?.startsWith('video/')||/\.(mp4|webm)(\?|$)/i.test(asset.url);return <figure className="rounded border border-stone-200 p-2"><figcaption className="mb-2 text-sm font-semibold">{label}</figcaption>{video?<video className="max-h-64 w-full object-contain" controls src={asset.url}/>:<img className="max-h-64 w-full object-contain" src={asset.url} alt={`${label}: ${asset.purpose}`}/>}</figure>; }

function MediaUploadForm({products,onStored}:{products:ProductFactoryState;onStored:(asset:Omit<MediaAsset,'id'|'status'|'createdAt'>)=>void}) {
 const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 return <form className="surface grid gap-4 p-6 md:grid-cols-2" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');const form=event.currentTarget;const data=new FormData(form);const upload=new FormData();upload.set('file',data.get('file')!);try{const response=await fetch('/api/media',{method:'POST',body:upload});const result=await response.json();if(!response.ok)throw new Error(result.error||'Upload falhou.');onStored({productId:String(data.get('productId')),url:result.url,kind:'ORIGINAL',purpose:String(data.get('purpose')),provenance:String(data.get('provenance')),checksum:result.checksum,mimeType:result.mimeType,bytes:result.bytes,rightsStatus:String(data.get('rightsStatus')) as MediaAsset['rightsStatus'],rightsHolder:String(data.get('rightsHolder')),rightsExpiresAt:String(data.get('rightsExpiresAt'))||undefined,destination:'Universal',format:'ORIGINAL',aspectRatio:'ORIGINAL'});form.reset()}catch(value){setError(value instanceof Error?value.message:'Upload falhou.')}finally{setBusy(false)}}}><h2 className="text-xl font-semibold md:col-span-2">Upload seguro de original</h2>{error&&<p role="alert" className="text-red-800 md:col-span-2">{error}</p>}<ProductSelect products={products}/><label>Arquivo — imagem ou vídeo até 10 MB<input required type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" className="ddf-input" /></label><label>Finalidade<input required name="purpose" className="ddf-input" /></label><label>Proveniência<input required name="provenance" className="ddf-input" /></label><RightsFields/><button className="ddf-button md:col-span-2" disabled={busy}>{busy?'Enviando…':'Armazenar e revisar'}</button></form>;
}
