'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {causalAudit,deriveOperationalAlerts,queueCanBeReprocessed,type OperationalSnapshot} from '@/lib/observability';

type AuditEvent={id:string;occurredAt:string;actor:string;action:string;entityType:string;entityId:string;correlationId:string;reason?:string|null;metadata:Record<string,unknown>};
const empty:OperationalSnapshot={generatedAt:'',latencyMs:0,outbox:{},queue:[],audit:{count:0,latest:null},state:[]};

export function ObservabilityWorkspace(){
 const [snapshot,setSnapshot]=useState(empty);const [events,setEvents]=useState<AuditEvent[]>([]);const [status,setStatus]=useState<'loading'|'online'|'offline'>('loading');const [correlation,setCorrelation]=useState<string|null>(null);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');
 const refresh=useCallback(async()=>{try{const[system,audit]=await Promise.all([fetch('/api/system',{cache:'no-store'}),fetch('/api/audit?limit=250',{cache:'no-store'})]);if(!system.ok||!audit.ok)throw new Error();setSnapshot(await system.json());setEvents((await audit.json()).events??[]);setStatus('online')}catch{setStatus('offline')}},[]);
 useEffect(()=>{const initial=window.setTimeout(()=>void refresh(),0);const timer=window.setInterval(()=>void refresh(),30000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[refresh]);
 const alerts=useMemo(()=>deriveOperationalAlerts(snapshot),[snapshot]);const visible=useMemo(()=>causalAudit(events,correlation),[events,correlation]);
 async function operate(action:'drain'|'reprocess',eventId?:string,correlationId?:string|null){setBusy(eventId??action);setMessage('');try{const response=await fetch('/api/system',{method:'POST',headers:{'content-type':'application/json','x-ddf-role':'ADMIN'},body:JSON.stringify({action,eventId,correlationId})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage(action==='drain'?`${data.processed??0} evento(s) processado(s).`:'Evento devolvido à fila com segurança.');await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Operação indisponível.')}finally{setBusy(null)}}
 return <div className="space-y-6"><header><p className="eyebrow">Sistema / rastreabilidade</p><h1 className="display-title">Auditoria & Observabilidade</h1><p className="lede">Navegação causal, saúde das filas e recuperação operacional em um único painel.</p></header>
 <section className="surface flex flex-wrap items-center justify-between gap-4 p-5"><div><strong>{status==='online'?'Monitoramento online':status==='loading'?'Carregando telemetria…':'Monitoramento indisponível'}</strong><p className="mt-1 text-sm text-gray-600">Atualização automática a cada 30 segundos · latência {snapshot.latencyMs} ms</p></div><button className="rounded bg-black px-4 py-2 text-sm text-white disabled:opacity-50" disabled={busy!==null||status!=='online'} onClick={()=>void operate('drain')}>{busy==='drain'?'Processando…':'Processar fila agora'}</button></section>
 {message&&<p role="status" className="surface p-4 text-sm">{message}</p>}
 <section><h2 className="text-xl font-semibold">Alertas internos</h2><div className="mt-3 grid gap-3 lg:grid-cols-3">{alerts.length?alerts.map(a=><article key={a.code} role={a.severity==='critical'?'alert':undefined} className={`surface border-l-4 p-4 ${a.severity==='critical'?'border-red-600':a.severity==='warning'?'border-amber-500':'border-blue-500'}`}><strong className="text-sm uppercase">{a.severity}</strong><p className="mt-1 text-sm">{a.message}</p></article>):<p className="surface p-4 text-sm">Nenhum alerta operacional ativo.</p>}</div></section>
 <section><h2 className="text-xl font-semibold">Filas, retries e falhas</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{['PENDING','PROCESSING','PUBLISHED','FAILED','DEAD'].map(key=><article className="surface p-4" key={key}><p className="text-xs text-gray-600">{key}</p><strong className="mt-2 block text-3xl">{snapshot.outbox[key]??0}</strong></article>)}</div><div className="mt-3 space-y-3">{snapshot.queue.filter(q=>q.status!=='PUBLISHED').map(q=><article className="surface p-4" key={q.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{q.topic}</strong><p className="text-sm text-gray-600">{q.status} · {q.attempts} tentativa(s) · {q.aggregateType}/{q.aggregateId}</p>{q.lastError&&<p className="mt-1 text-sm text-red-700">{q.lastError}</p>}</div>{queueCanBeReprocessed(q)&&<button className="rounded border border-stone-300 px-3 py-2 text-sm disabled:opacity-50" disabled={busy!==null} onClick={()=>void operate('reprocess',q.id,q.correlationId)}>{busy===q.id?'Reprocessando…':'Reprocessar'}</button>}</div></article>)}{!snapshot.queue.some(q=>q.status!=='PUBLISHED')&&<p className="surface p-4 text-sm">Fila sem pendências.</p>}</div></section>
 <section><h2 className="text-xl font-semibold">Estado e freshness</h2><div className="mt-3 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{snapshot.state.map(item=><article className="surface p-4" key={item.namespace}><div className="flex justify-between gap-3"><strong>{item.namespace}</strong><span className={`rounded px-2 py-1 text-xs ${item.stale?'bg-amber-100 text-amber-900':'bg-emerald-100 text-emerald-900'}`}>{item.stale?'STALE':'ATUAL'}</span></div><p className="mt-2 text-sm">Revisão {item.revision}</p><time className="text-xs text-gray-600">{new Date(item.updatedAt).toLocaleString('pt-BR')}</time></article>)}</div></section>
 <section><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Linha causal</h2><p className="mt-1 text-sm text-gray-600">Evento → cálculo/job → entidade, unidos pelo correlation ID.</p></div>{correlation&&<button className="text-sm underline" onClick={()=>setCorrelation(null)}>Limpar filtro causal</button>}</div><div className="mt-3 space-y-3">{visible.map(event=><article className="surface p-4" key={event.id}><div className="flex flex-wrap justify-between gap-2"><strong>{event.action}</strong><time className="text-xs text-gray-600">{new Date(event.occurredAt).toLocaleString('pt-BR')}</time></div><p className="mt-1 text-sm">{event.entityType}: {event.entityId}</p><button className="mt-2 break-all text-left text-xs text-gray-600 underline" onClick={()=>setCorrelation(event.correlationId)}>correlação {event.correlationId}</button></article>)}{!visible.length&&<p className="surface p-4 text-sm">Nenhum evento para esta correlação.</p>}</div></section></div>
}
