'use client';
import { useEffect, useState, useSyncExternalStore } from 'react';
import { emptyIntake, INTAKE_STORAGE_KEY, type IntakeState } from '@/lib/intake';
import { emptyMedia, MEDIA_STORAGE_KEY, type MediaState } from '@/lib/media-factory';
import { emptyPricing, PRICING_STORAGE_KEY, type PricingState } from '@/lib/pricing';
import { emptyProductFactory, PRODUCT_STORAGE_KEY, type ProductFactoryState } from '@/lib/product-factory';
import { emptyOrders, ORDER_STORAGE_KEY, type OrderState } from '@/lib/orders';
const keys=[INTAKE_STORAGE_KEY,PRODUCT_STORAGE_KEY,MEDIA_STORAGE_KEY,PRICING_STORAGE_KEY,ORDER_STORAGE_KEY];
function subscribe(cb:()=>void){window.addEventListener('storage',cb);for(const name of ['ddf-intake-change','ddf-products-change','ddf-media-change','ddf-pricing-change','ddf-orders-change'])window.addEventListener(name,cb);return()=>{window.removeEventListener('storage',cb);for(const name of ['ddf-intake-change','ddf-products-change','ddf-media-change','ddf-pricing-change','ddf-orders-change'])window.removeEventListener(name,cb)}}
function snapshot(){try{return keys.map(k=>localStorage.getItem(k)??'').join('\n')}catch{return'unavailable'}}
function useData(){const raw=useSyncExternalStore(subscribe,snapshot,()=>null);try{const[i,p,m,r,o]=(raw??'').split('\n');return{intake:i?JSON.parse(i) as IntakeState:emptyIntake,products:p?JSON.parse(p) as ProductFactoryState:emptyProductFactory,media:m?JSON.parse(m) as MediaState:emptyMedia,pricing:r?JSON.parse(r) as PricingState:emptyPricing,orders:o?JSON.parse(o) as OrderState:emptyOrders,error:''}}catch{return{intake:emptyIntake,products:emptyProductFactory,media:emptyMedia,pricing:emptyPricing,orders:emptyOrders,error:'Dados locais inválidos.'}}}
type BackendAuditEvent = { id:string; occurredAt:string; actor:string; action:string; entityType:string; entityId:string; correlationId:string; metadata:Record<string,unknown> };
export function AuditWorkspace(){
 const d=useData();const[backend,setBackend]=useState<BackendAuditEvent[]>([]);const[backendState,setBackendState]=useState<'loading'|'online'|'offline'>('loading');
 useEffect(()=>{let active=true;fetch('/api/audit?limit=100',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{if(active){setBackend(data.events??[]);setBackendState('online')}}).catch(()=>active&&setBackendState('offline'));return()=>{active=false}},[]);
 const local=[...d.intake.events.map(e=>({id:e.id,at:e.at,title:e.name,detail:`${e.before??'ENTRADA'} → ${e.after}`,actor:e.actor,correlation:''})),...d.products.events.map(e=>({id:e.id,at:e.at,title:d.products.products.find(p=>p.id===e.productId)?.universalTitle??'Produto',detail:`${e.action} · versão ${e.version}`,actor:e.actor,correlation:''})),...d.media.assets.map(a=>({id:a.id,at:a.createdAt,title:'Ativo de mídia',detail:`${a.kind} · ${a.status} · ${a.purpose}`,actor:'Aprovador · controlado',correlation:''})),...d.pricing.calculations.map(c=>({id:c.id,at:c.at,title:'Cálculo de preço',detail:`${c.status} · versão ${c.version}${c.reason?` · ${c.reason}`:''}`,actor:'Margin Guard · controlado',correlation:''}))];
 const server=backend.map(e=>({id:e.id,at:e.occurredAt,title:`${e.entityType}: ${e.entityId}`,detail:`${e.action} · revisão ${String(e.metadata?.revision??'—')}`,actor:e.actor,correlation:e.correlationId}));
 const events=[...server,...local].sort((a,b)=>b.at.localeCompare(a.at));
 return <div className="space-y-6"><header><p className="eyebrow">Sistema / rastreabilidade</p><h1 className="display-title">Auditoria & Eventos</h1><p className="lede">Decisões e mudanças da fábrica em uma única linha do tempo.</p></header><p className="surface p-4 text-sm">Audit trail do backend: <strong>{backendState==='online'?'online e imutável':backendState==='loading'?'carregando…':'indisponível'}</strong>. Eventos locais continuam visíveis para reconciliação.</p>{d.error&&<p role="alert">{d.error}</p>}{events.length===0?<p className="surface p-8">Nenhum evento registrado.</p>:events.map(e=><article className="surface p-5" key={`${e.id}-${e.detail}`}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{e.title}</h2><time className="text-xs text-gray-600">{new Date(e.at).toLocaleString('pt-BR')}</time></div><p className="mt-2">{e.detail}</p><p className="mt-2 text-xs text-gray-600">{e.actor}{e.correlation&&` · correlação ${e.correlation}`}</p></article>)}</div>
}
export function IntelligenceWorkspace(){const d=useData();const ready=d.products.products.filter(p=>p.status==='PRONTO').length;const safe=new Set(d.pricing.calculations.filter(c=>c.status==='CALCULADO').map(c=>c.productId)).size;const completed=d.orders.orders.filter(order=>order.status==='ENVIADO');const revenue=completed.reduce((sum,order)=>sum+order.salePrice,0);const cost=completed.reduce((sum,order)=>sum+order.costSnapshot,0);const contribution=revenue-cost;const margin=revenue>0?contribution/revenue*100:null;const midpoint=Math.ceil(completed.length/2);const recent=completed.slice(0,midpoint).reduce((sum,order)=>sum+order.salePrice,0);const earlier=completed.slice(midpoint).reduce((sum,order)=>sum+order.salePrice,0);const thermometer=completed.length<2?'Sem janela suficiente':recent>earlier*1.05?'Acelerando':recent<earlier*.95?'Desacelerando':'Estável';const commercial=[['Faturamento',revenue?`R$ ${revenue.toFixed(2)}`:'Sem dados'],['Contribuição',revenue?`R$ ${contribution.toFixed(2)}`:'Sem dados'],['Margem realizada',margin!==null?`${margin.toFixed(1)}%`:'Sem dados']];return <div className="space-y-6"><header><p className="eyebrow">Dados / decisão</p><h1 className="display-title">Intelligence Room</h1><p className="lede">Receita, custo e rentabilidade separados, com evidência operacional.</p></header><p className="surface p-4 text-sm">Valores comerciais usam somente pedidos enviados registrados na DDF. Ausência de venda aparece como “sem dados”, nunca como zero.</p><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Candidatos',d.intake.candidates.length],['Produtos em produção',d.products.products.length-ready],['Produtos prontos',ready],['Produtos com preço seguro',safe]].map(([label,value])=><article className="surface p-6" key={label}><p className="text-sm text-gray-600">{label}</p><strong className="mt-3 block text-4xl">{value}</strong></article>)}</section><section className="surface p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">Indicadores comerciais</h2><span className="rounded bg-stone-200 px-3 py-1 text-sm">Termômetro: {thermometer}</span></div><div className="mt-4 grid gap-4 sm:grid-cols-3">{commercial.map(([label,value])=><div className="border border-stone-200 p-4" key={label}><p>{label}</p><strong className="mt-2 block">{value}</strong><small>{completed.length?`${completed.length} pedido(s) enviado(s)`:'Nenhuma venda conectada'}</small></div>)}</div></section></div>}
