'use client';
import { useSyncExternalStore } from 'react';
import { emptyIntake, INTAKE_STORAGE_KEY, type IntakeState } from '@/lib/intake';
import { emptyMedia, MEDIA_STORAGE_KEY, type MediaState } from '@/lib/media-factory';
import { emptyPricing, PRICING_STORAGE_KEY, type PricingState } from '@/lib/pricing';
import { emptyProductFactory, PRODUCT_STORAGE_KEY, type ProductFactoryState } from '@/lib/product-factory';
const keys=[INTAKE_STORAGE_KEY,PRODUCT_STORAGE_KEY,MEDIA_STORAGE_KEY,PRICING_STORAGE_KEY];
function subscribe(cb:()=>void){window.addEventListener('storage',cb);for(const name of ['ddf-intake-change','ddf-products-change','ddf-media-change','ddf-pricing-change'])window.addEventListener(name,cb);return()=>{window.removeEventListener('storage',cb);for(const name of ['ddf-intake-change','ddf-products-change','ddf-media-change','ddf-pricing-change'])window.removeEventListener(name,cb)}}
function snapshot(){try{return keys.map(k=>localStorage.getItem(k)??'').join('\n')}catch{return'unavailable'}}
function useData(){const raw=useSyncExternalStore(subscribe,snapshot,()=>null);try{const[i,p,m,r]=(raw??'').split('\n');return{intake:i?JSON.parse(i) as IntakeState:emptyIntake,products:p?JSON.parse(p) as ProductFactoryState:emptyProductFactory,media:m?JSON.parse(m) as MediaState:emptyMedia,pricing:r?JSON.parse(r) as PricingState:emptyPricing,error:''}}catch{return{intake:emptyIntake,products:emptyProductFactory,media:emptyMedia,pricing:emptyPricing,error:'Dados locais inválidos.'}}}
export function AuditWorkspace(){const d=useData();const events=[...d.intake.events.map(e=>({id:e.id,at:e.at,title:e.name,detail:`${e.before??'ENTRADA'} → ${e.after}`,actor:e.actor})),...d.products.events.map(e=>({id:e.id,at:e.at,title:d.products.products.find(p=>p.id===e.productId)?.universalTitle??'Produto',detail:`${e.action} · versão ${e.version}`,actor:e.actor})),...d.media.assets.map(a=>({id:a.id,at:a.createdAt,title:'Ativo de mídia',detail:`${a.kind} · ${a.status} · ${a.purpose}`,actor:'Aprovador · demonstração'})),...d.pricing.calculations.map(c=>({id:c.id,at:c.at,title:'Cálculo de preço',detail:`${c.status} · versão ${c.version}${c.reason?` · ${c.reason}`:''}`,actor:'Margin Guard · demonstração'}))].sort((a,b)=>b.at.localeCompare(a.at));return <div className="space-y-6"><header><p className="eyebrow">Sistema / rastreabilidade</p><h1 className="display-title">Auditoria & Eventos</h1><p className="lede">Decisões e mudanças da fábrica em uma única linha do tempo.</p></header>{d.error&&<p role="alert">{d.error}</p>}{events.length===0?<p className="surface p-8">Nenhum evento registrado.</p>:events.map(e=><article className="surface p-5" key={`${e.id}-${e.detail}`}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{e.title}</h2><time className="text-xs text-gray-600">{new Date(e.at).toLocaleString('pt-BR')}</time></div><p className="mt-2">{e.detail}</p><p className="mt-2 text-xs text-gray-600">{e.actor}</p></article>)}</div>}
export function IntelligenceWorkspace(){const d=useData();const ready=d.products.products.filter(p=>p.status==='PRONTO').length;const safe=new Set(d.pricing.calculations.filter(c=>c.status==='CALCULADO').map(c=>c.productId)).size;return <div className="space-y-6"><header><p className="eyebrow">Dados / decisão</p><h1 className="display-title">Intelligence Room</h1><p className="lede">Leitura operacional baseada somente nos dados disponíveis.</p></header><p className="surface p-4 text-sm">Receita, vendas, lucro e rentabilidade aparecem como “sem dados” até existirem eventos transacionais. Ausência nunca é apresentada como zero.</p><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Candidatos',d.intake.candidates.length],['Produtos em produção',d.products.products.length-ready],['Produtos prontos',ready],['Produtos com preço seguro',safe]].map(([label,value])=><article className="surface p-6" key={label}><p className="text-sm text-gray-600">{label}</p><strong className="mt-3 block text-4xl">{value}</strong></article>)}</section><section className="surface p-6"><h2 className="text-xl font-semibold">Indicadores comerciais</h2><div className="mt-4 grid gap-4 sm:grid-cols-3">{['Faturamento','Lucro real','Margem realizada'].map(x=><div className="border border-stone-200 p-4" key={x}><p>{x}</p><strong className="mt-2 block text-gray-500">Sem dados</strong><small>Nenhuma venda conectada</small></div>)}</div></section></div>}
