'use client';
import { useState, useSyncExternalStore } from 'react';
import { calculatePrice, emptyPricing, PRICING_STORAGE_KEY, type PricingState } from '@/lib/pricing';
import { emptyProductFactory, PRODUCT_STORAGE_KEY, type ProductFactoryState } from '@/lib/product-factory';
const eventName='ddf-pricing-change';
function subscribe(cb:()=>void){window.addEventListener('storage',cb);window.addEventListener(eventName,cb);return()=>{window.removeEventListener('storage',cb);window.removeEventListener(eventName,cb)}}
function snapshot(){try{return `${localStorage.getItem(PRODUCT_STORAGE_KEY)??''}\n${localStorage.getItem(PRICING_STORAGE_KEY)??''}`}catch{return'unavailable'}}
const number=(d:FormData,name:string)=>Number(d.get(name));
const fields=[['supplierCost','Custo do produto'],['shipping','Frete e logística'],['taxes','Impostos'],['fixedFees','Tarifas fixas'],['operatingCost','Custo operacional'],['reserve','Reserva / buffer'],['channelFeePercent','Comissão do canal (%)'],['paymentFeePercent','Taxa de pagamento (%)'],['targetMarginPercent','Margem alvo (%)'],['minimumMarginPercent','Margem mínima (%)']] as const;
export function PricingWorkspace(){
 const raw=useSyncExternalStore(subscribe,snapshot,()=>null);let products:ProductFactoryState=emptyProductFactory;let pricing:PricingState=emptyPricing;let loadError='';
 try{if(raw){const[p,c]=raw.split('\n');products=p?JSON.parse(p):emptyProductFactory;pricing=c?JSON.parse(c):emptyPricing;if(!Array.isArray(products.products)||!Array.isArray(pricing.calculations))throw new Error()}}catch{loadError='Dados locais inválidos; simulação bloqueada.'}
 const[error,setError]=useState('');const[message,setMessage]=useState('');
 function save(next:PricingState){if(snapshot()!==raw)throw new Error('Os dados mudaram em outra aba. Revise antes de repetir.');localStorage.setItem(PRICING_STORAGE_KEY,JSON.stringify(next));window.dispatchEvent(new Event(eventName));setError('')}
 const ready=products.products.filter(p=>p.status==='PRONTO');
 return <div className="space-y-6"><header><p className="eyebrow">Economia / proteção</p><h1 className="display-title">Pricing & Margin Guard</h1><p className="lede">Simule preços explicáveis antes de qualquer decisão de distribuição.</p></header><p className="surface p-4 text-sm">Dados controlados. O cálculo não publica nem atualiza preços externos; fornecedor, marca e canal ainda não foram escolhidos.</p>{(error||loadError)&&<p role="alert" className="border border-red-300 bg-red-50 p-4 text-red-800">{error||loadError}</p>}<p role="status" className="text-sm text-green-800">{message}</p>
 {!loadError&&<form className="surface grid gap-4 p-6" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);try{save(calculatePrice(pricing,{productId:String(d.get('productId')),currency:'BRL',supplierCost:number(d,'supplierCost'),shipping:number(d,'shipping'),taxes:number(d,'taxes'),fixedFees:number(d,'fixedFees'),operatingCost:number(d,'operatingCost'),reserve:number(d,'reserve'),channelFeePercent:number(d,'channelFeePercent'),paymentFeePercent:number(d,'paymentFeePercent'),targetMarginPercent:number(d,'targetMarginPercent'),minimumMarginPercent:number(d,'minimumMarginPercent')},crypto.randomUUID(),new Date().toISOString()));setMessage('Simulação versionada. Nenhum preço foi publicado.')}catch(x){setError(x instanceof Error?x.message:'Falha no cálculo.')}}}><h2 className="text-xl font-semibold">Nova simulação</h2><label>Produto pronto<select required name="productId" className="ddf-input"><option value="">Selecione</option>{ready.map(p=><option key={p.id} value={p.id}>{p.universalTitle}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2">{fields.map(([name,label])=><label key={name}>{label}<input required min="0" step="0.01" type="number" name={name} className="ddf-input" /></label>)}</div><button className="ddf-button" disabled={!ready.length}>Calcular e proteger margem</button>{!ready.length&&<p className="text-sm text-gray-600">Finalize ao menos um produto com mídia aprovada para simular.</p>}</form>}
 <section className="space-y-3">{pricing.calculations.length===0&&<p className="surface p-8">Nenhuma simulação registrada.</p>}{pricing.calculations.map(c=>{const p=products.products.find(x=>x.id===c.productId);return <article key={c.id} className="surface space-y-4 p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{p?.universalTitle??'Produto não encontrado'}</h2><p className="text-sm text-gray-600">Versão {c.version} · {new Date(c.at).toLocaleString('pt-BR')}</p></div><span className={`rounded px-3 py-1 text-sm ${c.status==='CALCULADO'?'bg-green-100 text-green-800':'bg-red-100 text-red-800'}`}>{c.status}</span></div>{c.status==='BLOQUEADO'?<p className="font-semibold text-red-800">{c.reason}</p>:<div className="grid gap-4 sm:grid-cols-3"><div><small>Custo real</small><strong className="block text-2xl">R$ {c.totalFixedCost.toFixed(2)}</strong></div><div><small>Preço mínimo seguro</small><strong className="block text-2xl">R$ {c.minimumSafePrice?.toFixed(2)}</strong></div><div><small>Preço sugerido</small><strong className="block text-2xl">R$ {c.suggestedPrice?.toFixed(2)}</strong></div></div>}<details><summary className="cursor-pointer font-semibold">Ver componentes do cálculo</summary><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p>Produto: R$ {c.supplierCost.toFixed(2)}</p><p>Frete: R$ {c.shipping.toFixed(2)}</p><p>Impostos: R$ {c.taxes.toFixed(2)}</p><p>Custos e reserva: R$ {(c.fixedFees+c.operatingCost+c.reserve).toFixed(2)}</p><p>Taxas variáveis: {(c.variableRate*100).toFixed(2)}%</p><p>Margens alvo/mínima: {c.targetMarginPercent}% / {c.minimumMarginPercent}%</p></div></details></article>})}</section></div>
}
