'use client';
import {useState} from 'react';
import {command,errorMessage,sendCommand,type Command} from '@/lib/command-client';
import {useServerStates} from '@/components/use-server-states';
import {ProductListFilters,filterOptions} from '@/components/product-list-filters';
import {emptyProductFilters,matchesProductFilters,type ProductFilters} from '@/lib/product-filters';
const NAMESPACES=['products','pricing','intake'] as const;
const number=(d:FormData,n:string)=>Number(d.get(n));
const moneyFields=[['supplierCost','Custo do produto'],['shipping','Frete e logística'],['taxes','Impostos'],['fixedFees','Tarifas fixas'],['operatingCost','Custo operacional'],['reserve','Reserva / buffer'],['channelFeePercent','Comissão do canal (%)'],['paymentFeePercent','Taxa de pagamento (%)'],['targetMarginPercent','Margem alvo (%)'],['minimumMarginPercent','Margem mínima (%)']] as const;
export function PricingWorkspace(){
const {states,status,fromCache,error:loadError,reload}=useServerStates(NAMESPACES);const products=states.products;const pricing=states.pricing;
const[filters,setFilters]=useState<ProductFilters>(emptyProductFilters);const[priceStatus,setPriceStatus]=useState('');const[channel,setChannel]=useState('');const[store,setStore]=useState('');const[approval,setApproval]=useState('');const[selected,setSelected]=useState<Set<string>>(new Set());const[bulkBusy,setBulkBusy]=useState(false);
const updateFilters=(patch:Partial<ProductFilters>)=>{setFilters(current=>({...current,...patch}));setSelected(new Set());};
const candidates=new Map(states.intake.candidates.map(candidate=>[candidate.id,candidate]));const filteredProductIds=new Set(products.products.filter(product=>matchesProductFilters(product,candidates.get(product.candidateId),filters)).map(product=>product.id));
const calculations=pricing.calculations.filter(calculation=>filteredProductIds.has(calculation.productId)&&(!priceStatus||calculation.status===priceStatus)&&(!channel||calculation.channel===channel)&&(!store||calculation.store===store)&&(!approval||calculation.approval===approval));
const selectedCalculations=calculations.filter(calculation=>selected.has(calculation.id));const allSelected=calculations.length>0&&selectedCalculations.length===calculations.length;
const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
async function bulk(type:'pricing.approve'|'pricing.releaseQuarantine') {const eligible=selectedCalculations.filter(calculation=>type==='pricing.approve'?calculation.status==='CALCULADO'&&calculation.approval!=='APROVADO':calculation.status==='QUARENTENA');if(!eligible.length||bulkBusy)return;setBulkBusy(true);setError('');let completed=0;try{for(const calculation of eligible){await sendCommand(command(type,{calculationId:calculation.id,...(type==='pricing.releaseQuarantine'?{reason:releaseReason}:{})}));completed++;}setSelected(new Set());setMessage(`${completed} cálculo(s) ${type==='pricing.approve'?'aprovado(s) internamente':'liberado(s) da quarentena'}. Nenhum preço foi publicado.`);}catch(value){setError(`${completed} cálculo(s) concluído(s). ${errorMessage(value)}`);}finally{setBulkBusy(false);reload();}}
const[error,setError]=useState('');const[message,setMessage]=useState('');const[releaseReason,setReleaseReason]=useState('Variação analisada e economicamente justificada.');function action(cmd:Command,msg:string){sendCommand(cmd).then(()=>{setError('');setMessage(msg);reload()},x=>setError(errorMessage(x,'Operação indisponível.')))}const ready=products.products.filter(p=>p.status==='PRONTO'&&filteredProductIds.has(p.id));return <div className="space-y-6"><header><p className="eyebrow">Economia / proteção</p><h1 className="display-title">Pricing & Margin Guard</h1><p className="lede">Preço multicontexto, fontes versionadas, quarentena e aprovação explícita.</p></header><p className="surface p-4 text-sm">O cálculo não publica preços externos. FX, impostos e tarifas ficam registrados com a versão da fonte usada.</p>{(error||loadError)&&<p role="alert" className="border border-red-300 bg-red-50 p-4 text-red-800">{error||loadError}</p>}<p role="status" className="text-sm text-green-800">{message}</p>
<ProductListFilters filters={filters} onChange={updateFilters} categories={filterOptions(products.products.map(product=>product.category))} suppliers={filterOptions(states.intake.candidates.map(candidate=>candidate.supplier?.name))}/>
<section className="surface flex flex-wrap items-center gap-3 p-4"><label>Estado do preço<select className="ddf-input" value={priceStatus} onChange={e=>{setPriceStatus(e.target.value);setSelected(new Set());}}><option value="">Todos</option>{['CALCULADO','QUARENTENA','BLOQUEADO'].map(value=><option key={value}>{value}</option>)}</select></label><label>Canal<select className="ddf-input" value={channel} onChange={e=>{setChannel(e.target.value);setSelected(new Set());}}><option value="">Todos</option>{filterOptions(pricing.calculations.map(c=>c.channel)).map(value=><option key={value}>{value}</option>)}</select></label><label>Loja<select className="ddf-input" value={store} onChange={e=>{setStore(e.target.value);setSelected(new Set());}}><option value="">Todas</option>{filterOptions(pricing.calculations.map(c=>c.store)).map(value=><option key={value}>{value}</option>)}</select></label><label>Aprovação<select className="ddf-input" value={approval} onChange={e=>{setApproval(e.target.value);setSelected(new Set());}}><option value="">Todas</option>{filterOptions(pricing.calculations.map(c=>c.approval)).map(value=><option key={value}>{value}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={allSelected} disabled={bulkBusy||!calculations.length} onChange={()=>setSelected(allSelected?new Set():new Set(calculations.map(c=>c.id)))}/>Selecionar todos no filtro ({calculations.length})</label><span>{selectedCalculations.length} selecionado(s)</span><button className="ddf-button" disabled={bulkBusy||!selectedCalculations.some(c=>c.status==='CALCULADO'&&c.approval!=='APROVADO')} onClick={()=>bulk('pricing.approve')}>Aprovar preços selecionados</button><button className="ddf-button secondary" disabled={bulkBusy||!releaseReason.trim()||!selectedCalculations.some(c=>c.status==='QUARENTENA')} onClick={()=>bulk('pricing.releaseQuarantine')}>Liberar quarentena selecionada</button><button className="ddf-button secondary" onClick={()=>{setFilters(emptyProductFilters);setPriceStatus('');setChannel('');setStore('');setApproval('');setSelected(new Set());}}>Limpar filtros</button></section>
{status!=='ready'&&!fromCache&&<p>Carregando preços do servidor…</p>}
{!loadError&&<form className="surface grid gap-4 p-6" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);action(command('pricing.calculate',{input:{productId:String(d.get('productId')),currency:String(d.get('currency')),country:String(d.get('country')),channel:String(d.get('channel')),store:String(d.get('store')),offerId:String(d.get('offerId')),fxRate:number(d,'fxRate'),supplierCost:number(d,'supplierCost'),shipping:number(d,'shipping'),taxes:number(d,'taxes'),fixedFees:number(d,'fixedFees'),operatingCost:number(d,'operatingCost'),reserve:number(d,'reserve'),channelFeePercent:number(d,'channelFeePercent'),paymentFeePercent:number(d,'paymentFeePercent'),targetMarginPercent:number(d,'targetMarginPercent'),minimumMarginPercent:number(d,'minimumMarginPercent')}}),'Simulação versionada; nenhum preço foi publicado.')}}><h2 className="text-xl font-semibold">Nova simulação</h2><div className="grid gap-4 sm:grid-cols-3"><label>Produto pronto<select required name="productId" className="ddf-input"><option value="">Selecione</option>{ready.map(p=><option key={p.id} value={p.id}>{p.universalTitle}</option>)}</select></label>{[['currency','Moeda','BRL'],['country','País','BR'],['channel','Canal','sandbox'],['store','Loja','default'],['offerId','Oferta','oferta-padrao'],['fxRate','Taxa FX','1']].map(([name,label,value])=><label key={name}>{label}<input required name={name} defaultValue={value} type={name==='fxRate'?'number':'text'} min={name==='fxRate'?'0.000001':undefined} step={name==='fxRate'?'0.000001':undefined} className="ddf-input"/></label>)}</div><div className="grid gap-4 sm:grid-cols-2">{moneyFields.map(([name,label])=><label key={name}>{label}<input required min="0" step="0.01" type="number" name={name} className="ddf-input"/></label>)}</div><button className="ddf-button" disabled={!ready.length}>Calcular e proteger margem</button>{!ready.length&&<p className="text-sm text-gray-600">Finalize ao menos um produto com mídia aprovada para simular.</p>}</form>}
<section className="surface grid gap-4 p-4 sm:grid-cols-2"><p className="text-sm">Aprovações ficam registradas com o usuário autenticado e exigem papel ADMIN ou APPROVER.</p><label>Justificativa para liberar quarentena<input className="ddf-input" value={releaseReason} onChange={e=>setReleaseReason(e.target.value)}/></label></section>
<section className="space-y-3">{calculations.length===0&&<p className="surface p-8">Nenhuma simulação registrada.</p>}{calculations.map(c=>{const p=products.products.find(x=>x.id===c.productId);const badge=c.status==='CALCULADO'?'bg-green-100 text-green-800':c.status==='QUARENTENA'?'bg-amber-100 text-amber-900':'bg-red-100 text-red-800';return <article key={c.id} className="surface space-y-4 p-6"><div className="flex flex-wrap justify-between gap-3"><div><label className="flex items-center gap-2"><input type="checkbox" checked={selected.has(c.id)} disabled={bulkBusy} onChange={()=>toggle(c.id)} aria-label={`Selecionar preço de ${p?.universalTitle??c.productId}`}/><h2 className="text-xl font-semibold">{p?.universalTitle??'Produto não encontrado'}</h2></label><p className="text-sm text-gray-600">{[c.country,c.channel,c.store,c.offerId,c.currency].filter(Boolean).join(' · ')} · versão {c.version}</p></div><span className={`rounded px-3 py-1 text-sm ${badge}`}>{c.status} · {c.approval}</span></div>{c.reason&&<p className="font-semibold">{c.reason}</p>}{c.status!=='BLOQUEADO'&&<div className="grid gap-4 sm:grid-cols-3"><div><small>Custo real</small><strong className="block text-2xl">{c.currency} {c.totalFixedCost.toFixed(2)}</strong></div><div><small>Mínimo seguro</small><strong className="block text-2xl">{c.currency} {c.minimumSafePrice?.toFixed(2)}</strong></div><div><small>Sugerido</small><strong className="block text-2xl">{c.currency} {c.suggestedPrice?.toFixed(2)}</strong></div></div>}<div className="flex gap-3">{c.status==='QUARENTENA'&&<button className="ddf-button" onClick={()=>action(command('pricing.releaseQuarantine',{calculationId:c.id,reason:releaseReason}),'Quarentena liberada para aprovação.')}>Liberar quarentena</button>}{c.status==='CALCULADO'&&c.approval!=='APROVADO'&&<button className="ddf-button" onClick={()=>action(command('pricing.approve',{calculationId:c.id}),'Preço aprovado internamente; ainda não publicado.')}>Aprovar preço</button>}</div><details><summary className="cursor-pointer font-semibold">Cálculo e proveniência</summary><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p>Produto + frete × FX: {c.fxRate??1}</p><p>Taxas variáveis: {(c.variableRate*100).toFixed(2)}%</p><p>Margens alvo/mínima: {c.targetMarginPercent}% / {c.minimumMarginPercent}%</p><p>Fonte FX: {c.sources?.fx.provider??'legado'} · {c.sources?.fx.version??'n/a'}</p><p>Fonte fiscal: {c.sources?.tax.provider??'legado'} · {c.sources?.tax.version??'n/a'}</p><p>Fonte tarifas: {c.sources?.tariff.provider??'legado'} · {c.sources?.tariff.version??'n/a'}</p></div></details></article>})}</section></div>}
