'use client';

import { useEffect, useMemo, useState } from 'react';
import { emptyUniversalSpec, emptyTechnical, productCompletion, productGaps, productVersionDiff, type MasterProduct, type ProductFactoryState, type UniversalProductSpec } from '@/lib/product-factory';
import { command, errorMessage, sendCommand, type Command } from '@/lib/command-client';
import { candidateCard } from '@/lib/storefront';
import { baseTaxonomy } from '@/lib/taxonomy';
import { useServerStates } from '@/components/use-server-states';
import { ManualPilotExport } from '@/components/manual-pilot-export';
import { FiscalPanel } from '@/components/fiscal-form';
import { approvedStudioAssets } from '@/lib/media-factory';
import { availabilityLabels } from '@/lib/product-fiscal';
import { emptyProductFilters, matchesApprovedCandidateFilters, matchesProductFilters, productMissingTechnical, type ProductFilters } from '@/lib/product-filters';

// Read straight from the server: a stale or old-version browser cache can no longer block this screen.
const NAMESPACES = ['intake', 'products', 'media'] as const;
const lines = (value: FormDataEntryValue | null) => String(value ?? '').split('\n');
const queueLabels: Record<string, string> = { PENDING: 'na fila', PROCESSING: 'em execução', CONTINUING: 'leitura em andamento', COMPLETED: 'concluído', BLOCKED: 'bloqueado', FAILED: 'falhou', PENDENTE: 'na fila', PROCESSANDO: 'em execução', CONCLUIDO: 'concluído', BLOQUEADO: 'bloqueado', FALHOU: 'falhou' };
const cleanLines = (value: FormDataEntryValue | null) => lines(value).map(item=>item.trim()).filter(Boolean);
function parseRecord<T>(value: FormDataEntryValue|null, label:string):T { try { const parsed=JSON.parse(String(value||'{}')); if(!parsed||typeof parsed!=='object') throw new Error(); return parsed as T; } catch { throw new Error(`${label} deve conter JSON válido.`); } }
const numberField=(form:FormData,name:string)=>{const raw=String(form.get(name)??'').trim();if(!raw)return null;const value=Number(raw);if(!Number.isFinite(value)||value<=0)throw new Error('Medidas devem ser números positivos; deixe vazias quando não informadas.');return value;};
function readSpec(form:FormData):UniversalProductSpec { return {
  technical:{...emptyTechnical,dimensions:{lengthCm:numberField(form,'lengthCm'),widthCm:numberField(form,'widthCm'),heightCm:numberField(form,'heightCm')},weightGrams:numberField(form,'weightGrams'),packageDimensions:{lengthCm:numberField(form,'packageLengthCm'),widthCm:numberField(form,'packageWidthCm'),heightCm:numberField(form,'packageHeightCm')},packageWeightGrams:numberField(form,'packageWeightGrams'),model:String(form.get('model')||''),brand:String(form.get('brand')||''),features:cleanLines(form.get('features')),specifications:parseRecord(form.get('specifications'),'Especificações'),careInstructions:String(form.get('careInstructions')||''),includedItems:cleanLines(form.get('includedItems')),additionalFields:parseRecord(form.get('additionalFields'),'Campos adicionais')},
  sourceImages:cleanLines(form.get('sourceImages')),sourceUrl:String(form.get('sourceUrl')||''),
  variants: parseRecord<UniversalProductSpec['variants']>(form.get('variants'),'Variantes'), materials:cleanLines(form.get('materials')),colors:cleanLines(form.get('colors')),sizes:cleanLines(form.get('sizes')),
  seo:{title:String(form.get('seoTitle')||''),description:String(form.get('seoDescription')||'')}, compliance:{notes:String(form.get('complianceNotes')||''),certifications:cleanLines(form.get('certifications'))},
  localizations:parseRecord<UniversalProductSpec['localizations']>(form.get('localizations'),'Localizações'),destinationGaps:parseRecord<UniversalProductSpec['destinationGaps']>(form.get('destinationGaps'),'Gaps por destino')}; }

export function ProductFactoryWorkspace({ mode }: { mode: 'factory' | 'catalog' }) {
  const { states, status, fromCache, error: loadError, reload } = useServerStates(NAMESPACES);
  const data = { intake: states.intake, factory: states.products, media: states.media };
  const ready = status === 'ready' || fromCache;
  const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [filters, setFilters] = useState<ProductFilters>(emptyProductFilters);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [bulkBusy, setBulkBusy] = useState(false);
  const [archivePending, setArchivePending] = useState(false);
  const [archiveReason, setArchiveReason] = useState('Retirado da produção por decisão de curadoria');
  const [openId, setOpenId] = useState<string | null>(null);
  const candidates = useMemo(() => new Map(data.intake.candidates.map(c => [c.id, candidateCard(c)])), [data.intake.candidates]);
  const photoOf = (product: MasterProduct) => approvedStudioAssets(data.media,product.id)[0]?.url ?? candidates.get(product.candidateId)?.imageUrl ?? '';
  const sourceCandidates = new Map(data.intake.candidates.map(candidate => [candidate.id, candidate]));
  const allApproved = data.intake.candidates.filter(c => c.status === 'APROVADO' && !data.factory.products.some(p => p.candidateId === c.id));
  const approved = allApproved.filter(candidate => matchesApprovedCandidateFilters(candidate, filters));
  const areaProducts = data.factory.products.filter(product => mode === 'factory' || product.status === 'PRONTO');
  const studioCounts = new Map(areaProducts.map(product => [product.id, approvedStudioAssets(data.media, product.id).length]));
  const products = areaProducts.filter(product => matchesProductFilters(product, sourceCandidates.get(product.candidateId), filters, studioCounts.get(product.id)));
  const options = (values: (string | undefined)[]) => [...new Set(values.filter((value): value is string => !!value?.trim()))].sort((a, b) => a.localeCompare(b, 'pt-BR'));
  const categories = options([...areaProducts.map(product => product.category), ...allApproved.map(candidate => candidate.category)]);
  const suppliers = options([...areaProducts.map(product => sourceCandidates.get(product.candidateId)?.supplier?.name), ...allApproved.map(candidate => candidate.supplier?.name)]);
  const brands = options(areaProducts.map(product => product.spec?.technical?.brand));
  const selectedProducts = products.filter(product => selected.has(product.id));
  const editableSelection = selectedProducts.filter(product => product.status === 'EM_PRODUCAO' && !product.archivedAt);
  const incompleteSelection = editableSelection.filter(product => productGaps(product).length > 0);
  const readySelection = editableSelection.filter(product => !productGaps(product).length && (studioCounts.get(product.id) ?? 0) >= 4);
  const allSelected = products.length > 0 && selectedProducts.length === products.length;
  const updateFilters = (patch: Partial<ProductFilters>) => { setFilters(current => ({ ...current, ...patch })); setSelected(new Set()); setArchivePending(false); };
  const toggle = (id: string) => setSelected(current => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  async function delegateBulk(type: 'media.bulkSendToMedia' | 'products.bulkRequestCompletion', productIds: string[]) {
    if (bulkBusy || !productIds.length) return;
    setBulkBusy(true); setError(''); setMessage('');
    let sent = 0;
    try {
      for (let offset = 0; offset < productIds.length; offset += 200) {
        const batch = productIds.slice(offset, offset + 200);
        await sendCommand(command(type, { productIds: batch })); sent += batch.length;
      }
      setMessage(`${sent} produto(s) enviado(s) à fila de ${type === 'media.bulkSendToMedia' ? 'mídia' : 'complementação do cadastro'}. Os agentes executarão as etapas; pendências continuam visíveis até a conclusão.`);
      setSelected(new Set()); reload();
    } catch (cause) { setError(`${sent ? `${sent} produto(s) já enviado(s). ` : ''}${errorMessage(cause)}`); reload(); }
    finally { setBulkBusy(false); }
  }
  async function finalizeSelection(kind: 'archive' | 'ready') {
    if (bulkBusy) return;
    const targets = kind === 'archive' ? editableSelection : readySelection;
    if (!targets.length || (kind === 'archive' && !archiveReason.trim())) return;
    setBulkBusy(true); setError(''); setMessage(''); let sent = 0;
    try {
      if (kind === 'archive') {
        for (let offset = 0; offset < targets.length; offset += 200) {
          const batch = targets.slice(offset, offset + 200);
          await sendCommand(command('products.bulkArchive', { productIds: batch.map(product => product.id), reason: archiveReason })); sent += batch.length;
        }
      } else {
        for (const product of targets) { await sendCommand(command('products.markReady', { productId: product.id })); sent++; }
      }
      setMessage(`${sent} produto(s) ${kind === 'archive' ? 'arquivado(s). Histórico e originais preservados.' : 'marcado(s) como pronto(s), sem publicar na loja.'}`);
      setSelected(new Set()); setArchivePending(false); reload();
    } catch (cause) { setError(`${sent ? `${sent} produto(s) já processado(s). ` : ''}${errorMessage(cause)}`); reload(); }
    finally { setBulkBusy(false); }
  }
  const open = openId ? data.factory.products.find(p => p.id === openId) ?? null : null;
  function act(cmd: Command, success: string) { sendCommand(cmd).then(() => { setError(''); setMessage(success); setEditing(null); }, e => setError(errorMessage(e))); }
  return <div className="space-y-6">
    <header><p className="eyebrow">Produção / cadastro universal</p><h1 className="display-title">{mode === 'factory' ? 'Product Factory' : 'Produtos Disponíveis'}</h1><p className="lede">{mode === 'factory' ? 'Transforme candidatos aprovados em produtos mestres reutilizáveis.' : 'Catálogo de produtos prontos, ainda independentes de publicação.'}</p></header>
    <p className="surface p-4 text-sm">Produto mestre não contém fornecedor, preço, canal ou publicação. Essas decisões permanecem independentes.</p>
    {(error || loadError) && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 border border-red-300 bg-red-50 p-4 text-red-800"><span>{error || loadError}</span>{loadError && <button className="ddf-button secondary" onClick={reload}>Tentar de novo</button>}</div>}<p role="status" className="text-sm text-green-800">{message}</p>
    {!ready ? <p className="surface p-6 text-sm">Carregando dados do servidor…</p> : <>
    {mode === 'factory' && status === 'ready' && <ManualPilotExport candidates={data.intake.candidates.filter(candidate => candidate.status === 'APROVADO' || data.factory.products.some(product => product.candidateId === candidate.id && !product.archivedAt))} products={data.factory.products} />}
    {mode === 'factory' && <section className="space-y-3"><div className="section-heading"><div><h2>Fila aprovada</h2><p>{approved.length} de {allApproved.length} candidato(s) aprovado(s) no filtro aguardando produção.</p></div></div>
      {approved.length === 0 ? <p className="surface p-6 text-sm">Nenhum candidato aprovado aguardando produção.</p> : <ul className="grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6">{approved.map(c => { const card = candidates.get(c.id); return <li key={c.id} className="surface flex flex-col overflow-hidden"><Photo url={card?.imageUrl ?? ''} /><div className="flex flex-1 flex-col gap-2 p-3"><h3 className="line-clamp-2 text-sm font-semibold leading-snug" title={c.fullName || c.name}>{c.name}</h3><p className="text-xs text-[var(--muted)]">Aprovado na triagem · {card?.supplier}</p><button className="ddf-button mt-auto !w-full !px-3 text-sm" onClick={() => act(command('products.start', { candidateId: c.id }), 'Produção iniciada. Nenhuma operação externa foi acionada.')}>Iniciar produção</button></div></li>; })}</ul>}
    </section>}
    <section className="surface space-y-3 p-4" aria-label="Filtros de produtos">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-sm sm:col-span-2">Buscar produto<input className="ddf-input" type="search" value={filters.query} onChange={event => updateFilters({ query: event.target.value })} placeholder="Nome, categoria, fornecedor, marca ou SKU" /></label>
        <label className="text-sm">Categoria<select className="ddf-input" value={filters.category} onChange={event => updateFilters({ category: event.target.value })}><option value="">Todas as categorias</option>{categories.map(value => <option key={value}>{value}</option>)}</select></label>
        <label className="text-sm">Fornecedor de origem<select className="ddf-input" value={filters.supplier} onChange={event => updateFilters({ supplier: event.target.value })}><option value="">Todos os fornecedores</option>{suppliers.map(value => <option key={value}>{value}</option>)}</select></label>
        <label className="text-sm">Marca informada na ficha<select className="ddf-input" value={filters.brand} onChange={event => updateFilters({ brand: event.target.value })}><option value="">Todas as marcas</option>{brands.map(value => <option key={value}>{value}</option>)}</select></label>
        {mode === 'factory' && <label className="text-sm">Estado do cadastro<select className="ddf-input" value={filters.status} onChange={event => updateFilters({ status: event.target.value as ProductFilters['status'] })}><option value="">Todos os estados</option><option value="EM_PRODUCAO">Em produção</option><option value="PRONTO">Pronto</option></select></label>}
        <label className="text-sm">Pendência técnica<select className="ddf-input" value={filters.missing} onChange={event => updateFilters({ missing: event.target.value as ProductFilters['missing'] })}><option value="">Todas as fichas</option><option value="any">Qualquer pendência técnica</option><option value="dimensions">Dimensões incompletas</option><option value="weight">Peso incompleto</option><option value="material">Material ausente</option></select></label>
        <label className="text-sm">Arquivamento<select className="ddf-input" value={filters.archived ?? 'active'} onChange={event => updateFilters({ archived: event.target.value as ProductFilters['archived'] })}><option value="active">Somente ativos</option><option value="only">Somente arquivados</option><option value="all">Ativos e arquivados</option></select></label>
        <label className="text-sm">Fotos de estúdio<select className="ddf-input" value={filters.media} onChange={event => updateFilters({ media: event.target.value as ProductFilters['media'] })}><option value="">Todas</option><option value="pending">Menos de quatro aprovadas</option><option value="complete">Quatro ou mais aprovadas</option></select></label>
      </div>
      <div className="flex flex-wrap items-center gap-3"><button type="button" className={`ddf-button ${filters.eyewearOnly ? '' : 'secondary'}`} aria-pressed={filters.eyewearOnly} onClick={() => updateFilters({ eyewearOnly: !filters.eyewearOnly })}>Somente óculos</button><button type="button" className="ddf-button secondary" onClick={() => { setFilters(emptyProductFilters); setSelected(new Set()); }}>Limpar filtros</button><p className="text-sm text-[var(--muted)]" aria-live="polite">{products.length} de {areaProducts.length} produto(s) · {approved.length} candidato(s) aprovado(s) no filtro</p></div>
    </section>
    {mode === 'factory' && <section className="surface flex flex-wrap items-center gap-3 p-4" aria-label="Delegação em massa">
      <label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" className="h-5 w-5" checked={allSelected} disabled={!products.length || bulkBusy} onChange={() => setSelected(allSelected ? new Set() : new Set(products.map(product => product.id)))} />Selecionar todos no filtro ({products.length})</label>
      <span className="text-sm">{selectedProducts.length} selecionado(s)</span>
      <button type="button" className="ddf-button" disabled={bulkBusy || !incompleteSelection.length} onClick={() => delegateBulk('products.bulkRequestCompletion', incompleteSelection.map(product => product.id))}>{bulkBusy ? 'Enviando…' : `Delegar cadastro (${incompleteSelection.length})`}</button>
      <button type="button" className="ddf-button secondary" disabled={bulkBusy || !editableSelection.length} onClick={() => delegateBulk('media.bulkSendToMedia', editableSelection.map(product => product.id))}>Enviar para mídia ({editableSelection.length})</button>
      <button type="button" className="ddf-button secondary" disabled={bulkBusy || !readySelection.length} onClick={() => finalizeSelection('ready')}>Marcar prontos ({readySelection.length})</button>
      <button type="button" className="ddf-button secondary text-[var(--danger)]" disabled={bulkBusy || !editableSelection.length} onClick={() => setArchivePending(true)}>Arquivar selecionados ({editableSelection.length})</button>
      {archivePending && <form className="w-full space-y-3 rounded border border-amber-300 bg-amber-50 p-3 text-sm" onSubmit={event => { event.preventDefault(); void finalizeSelection('archive'); }}><p>Retirar <strong>{editableSelection.length} cadastro(s) em produção</strong> da lista ativa e das filas dos agentes? Histórico e fotos ficam preservados. Produtos prontos não são arquivados por esta ação.</p><label className="block">Motivo para auditoria<textarea className="ddf-input" value={archiveReason} onChange={event => setArchiveReason(event.target.value)} required maxLength={2000} rows={2} /></label><div className="flex flex-wrap gap-2"><button className="ddf-button" disabled={bulkBusy || !archiveReason.trim()}>{bulkBusy ? 'Arquivando…' : 'Confirmar arquivamento'}</button><button type="button" className="ddf-button secondary" disabled={bulkBusy} onClick={() => setArchivePending(false)}>Cancelar</button></div></form>}
      <p className="w-full text-xs text-[var(--muted)]">A seleção inclui todos os resultados do filtro. Produtos prontos ficam preservados; a delegação cria uma fila e não publica na loja.</p>
    </section>}
    {products.length === 0 && <div className="surface p-8"><h2 className="text-lg font-semibold">{areaProducts.length ? 'Nenhum produto corresponde aos filtros' : mode === 'catalog' ? 'Nenhum produto pronto' : 'A fábrica está vazia'}</h2><p className="mt-2">{areaProducts.length ? 'Ajuste os filtros ou use Limpar filtros para voltar à lista completa.' : mode === 'catalog' ? 'Finalize um cadastro mestre na Product Factory.' : 'Aprove um candidato na Sala de Triagem e inicie sua produção.'}</p></div>}
    <ul className="grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6" aria-label="Produtos mestres">{products.map(product => { const completion = productCompletion(product); const completionRequest = data.factory.completionRequests?.find(request => request.productId === product.id); const mediaRequest = data.media.productionRequests?.find(request => request.productId === product.id); return <li key={product.id} className={`surface relative flex flex-col overflow-hidden transition-shadow hover:shadow-lg ${selected.has(product.id) ? 'ring-2 ring-[var(--accent)]' : ''}`}>
      {mode === 'factory' && <label className="absolute left-2 top-2 z-10 grid h-10 w-10 place-items-center rounded-full bg-white/95 shadow"><input type="checkbox" className="h-5 w-5" aria-label={`Selecionar ${product.universalTitle}`} checked={selected.has(product.id)} disabled={bulkBusy} onChange={() => toggle(product.id)} /></label>}
      <button type="button" className="flex w-full flex-1 flex-col text-left" onClick={() => setOpenId(product.id)} aria-label={`Abrir ${product.universalTitle}`}>
        <div className="relative w-full"><Photo url={photoOf(product)} /><span className={`absolute bottom-2 left-2 rounded-full px-2 py-1 text-[11px] font-semibold ${product.status === 'PRONTO' ? 'bg-[var(--success-soft)] text-[var(--success)]' : 'bg-[var(--surface-strong)] text-[var(--ink)]'}`}>{product.status === 'PRONTO' ? 'Pronto' : product.archivedAt ? 'Arquivado' : 'Em produção'}</span>{product.availability && <span className={`absolute right-2 top-2 rounded-full px-2 py-1 text-[11px] font-bold ${product.availability === 'PRONTA_ENTREGA' ? 'bg-[var(--accent)] text-[var(--accent-ink)]' : 'bg-[var(--ink)] text-[var(--brand-branco)]'}`}>{availabilityLabels[product.availability]}</span>}</div>
        <div className="flex flex-1 flex-col gap-2 p-3"><h3 className="line-clamp-2 text-sm font-semibold leading-snug">{product.universalTitle}</h3><p className="truncate text-xs text-[var(--muted)]">{product.category || 'Categoria pendente'} · v{product.version}</p>
          <p className="text-xs text-[var(--muted)]">{Object.entries(productMissingTechnical(product)).filter(([, missing]) => missing).map(([field]) => ({ dimensions: 'Dimensões pendentes', weight: 'Peso pendente', material: 'Material pendente' }[field])).join(' · ') || 'Ficha técnica confirmada'}</p><p className="text-xs text-[var(--muted)]">{studioCounts.get(product.id) ?? 0}/4 fotos de estúdio aprovadas</p>{completionRequest && <p className="text-xs text-[var(--muted)]" title={completionRequest.reason}>Agente cadastro: {queueLabels[completionRequest.status] ?? completionRequest.status}</p>}{mediaRequest && <p className="text-xs text-[var(--muted)]" title={mediaRequest.error}>Agente mídia: {queueLabels[mediaRequest.status] ?? mediaRequest.status}</p>}<div className="mt-auto"><div className="flex justify-between text-xs"><span className="text-[var(--muted)]">Completude</span><strong>{completion}%</strong></div><div className="mt-1 h-1.5 rounded-full bg-stone-200"><div className="h-1.5 rounded-full bg-[var(--ink)]" style={{ width: `${completion}%` }} /></div></div></div>
      </button>{(sourceCandidates.get(product.candidateId)?.url || product.spec?.sourceUrl) && <a className="mx-3 mb-3 inline-flex min-h-9 items-center text-xs font-medium underline" href={sourceCandidates.get(product.candidateId)?.url || product.spec?.sourceUrl} target="_blank" rel="noopener noreferrer">Abrir produto no fornecedor ↗</a>}</li>; })}</ul>
    {open && <Panel title={open.universalTitle} onClose={() => { setOpenId(null); setEditing(null); }}><ProductCard product={open} versions={(data.factory.versions??[]).filter(v=>v.productId===open.id).sort((a,b)=>b.version-a.version)} editable={mode === 'factory' && !open.archivedAt} editing={editing === open.id} onEdit={() => setEditing(open.id)} onCancel={() => setEditing(null)} onSave={form => act(command('products.update', { productId: open.id, universalTitle: String(form.get('title')), category: String(form.get('category')), shortDescription: String(form.get('short')), longDescription: String(form.get('long')), bullets: lines(form.get('bullets')), benefits: lines(form.get('benefits')), tags: String(form.get('tags')).split(','), spec:readSpec(form) }), 'Rascunho salvo e nova versão registrada.')} onRestore={version=>act(command('products.restoreVersion',{productId:open.id,version}),`Versão ${version} restaurada como uma nova versão.`)} onReady={() => act(command('products.markReady', { productId: open.id }), 'Produto marcado como pronto. Nenhuma publicação foi iniciada.')} />{editing !== open.id && !open.archivedAt && <div className="border-t border-[var(--line)] p-4 sm:p-6"><FiscalPanel product={open} /></div>}</Panel>}
    </>}
  </div>;
}

/* eslint-disable-next-line @next/next/no-img-element -- supplier and media hosts are unknown; next/image would need each allow-listed. */
function Photo({ url }: { url: string }) { return <div className="aspect-square w-full overflow-hidden bg-stone-100">{url ? <img src={url} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-xs text-[var(--muted)]">Sem foto</div>}</div>; }

function Panel({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [onClose]);
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 sm:items-center sm:p-6" onClick={onClose}><div role="dialog" aria-modal="true" aria-label={title} className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-t-2xl bg-[var(--surface)] shadow-2xl sm:rounded-2xl" onClick={event => event.stopPropagation()}><div className="sticky top-0 z-10 flex justify-end border-b border-[var(--line)] bg-[var(--surface)] px-4 py-3"><button className="ddf-button secondary" onClick={onClose} autoFocus>Fechar</button></div><div className="[&>article]:border-0 [&>article]:shadow-none [&>form]:border-0">{children}</div></div></div>;
}

function ProductCard({ product, versions, editable, editing, onEdit, onCancel, onSave, onRestore, onReady }: { product: MasterProduct; versions:ProductFactoryState['versions']; editable: boolean; editing: boolean; onEdit: () => void; onCancel: () => void; onSave: (form: FormData) => void; onRestore:(version:number)=>void; onReady: () => void }) {
  const gaps = productGaps(product); const completion = productCompletion(product);
  const spec=product.spec??emptyUniversalSpec; const technical=spec.technical??emptyTechnical; const [fieldError,setFieldError]=useState('');
  if (editing) return <form className="surface grid gap-4 p-6" onSubmit={e => { e.preventDefault(); try{onSave(new FormData(e.currentTarget));setFieldError('');}catch(error){setFieldError(errorMessage(error));} }}><h2 className="text-xl font-semibold">Editar cadastro mestre</h2>{fieldError&&<p role="alert" className="text-red-700">{fieldError}</p>}<label>Título universal<input name="title" defaultValue={product.universalTitle} className="ddf-input" /></label><label>Categoria universal<input name="category" list="ddf-taxonomy" defaultValue={product.category} className="ddf-input" /><datalist id="ddf-taxonomy">{baseTaxonomy.map(node=><option value={node.name} key={node.id}/>)}</datalist></label><label>Descrição curta<textarea name="short" defaultValue={product.shortDescription} className="ddf-input" rows={2} /></label><label>Descrição longa<textarea name="long" defaultValue={product.longDescription} className="ddf-input" rows={4} /></label><label>Bullets — um por linha<textarea name="bullets" defaultValue={product.bullets.join('\n')} className="ddf-input" rows={4} /></label><label>Benefícios — um por linha<textarea name="benefits" defaultValue={product.benefits.join('\n')} className="ddf-input" rows={3} /></label><label>Tags — separadas por vírgula<input name="tags" defaultValue={product.tags.join(', ')} className="ddf-input" /></label>
    <fieldset className="grid gap-4 border-t border-stone-200 pt-4 sm:grid-cols-3"><legend className="text-lg font-semibold">Atributos universais</legend><label>Materiais — um por linha<textarea name="materials" defaultValue={spec.materials.join('\n')} className="ddf-input" /></label><label>Cores — uma por linha<textarea name="colors" defaultValue={spec.colors.join('\n')} className="ddf-input" /></label><label>Tamanhos — um por linha<textarea name="sizes" defaultValue={spec.sizes.join('\n')} className="ddf-input" /></label></fieldset>
    <fieldset className="grid gap-4 sm:grid-cols-3"><legend className="text-lg font-semibold">Ficha técnica completa</legend>{[['lengthCm','Comprimento do produto (cm)',technical.dimensions.lengthCm],['widthCm','Largura do produto (cm)',technical.dimensions.widthCm],['heightCm','Altura do produto (cm)',technical.dimensions.heightCm],['weightGrams','Peso do produto (g)',technical.weightGrams],['packageLengthCm','Comprimento da embalagem (cm)',technical.packageDimensions.lengthCm],['packageWidthCm','Largura da embalagem (cm)',technical.packageDimensions.widthCm],['packageHeightCm','Altura da embalagem (cm)',technical.packageDimensions.heightCm],['packageWeightGrams','Peso com embalagem (g)',technical.packageWeightGrams]].map(([name,label,value])=><label key={String(name)}>{label}<input type="number" min="0.001" step="any" name={String(name)} defaultValue={value??''} className="ddf-input" placeholder="Não informado pelo fornecedor" /></label>)}<label>Marca<input name="brand" defaultValue={technical.brand} className="ddf-input" /></label><label>Modelo<input name="model" defaultValue={technical.model} className="ddf-input" /></label><label>Características — uma por linha<textarea name="features" defaultValue={technical.features.join('\n')} className="ddf-input" /></label><label>Itens inclusos — um por linha<textarea name="includedItems" defaultValue={technical.includedItems.join('\n')} className="ddf-input" /></label><label>Cuidados e conservação<textarea name="careInstructions" defaultValue={technical.careInstructions} className="ddf-input" /></label><label className="sm:col-span-3">Especificações do fornecedor (JSON)<textarea name="specifications" defaultValue={JSON.stringify(technical.specifications,null,2)} className="ddf-input font-mono text-xs" rows={6} /></label><label className="sm:col-span-3">Campos técnicos adicionais (JSON; adicione qualquer atributo)<textarea name="additionalFields" defaultValue={JSON.stringify(technical.additionalFields,null,2)} className="ddf-input font-mono text-xs" rows={4} /></label><p className="sm:col-span-3 text-sm text-[var(--muted)]">Não estime medidas. Produto e embalagem são campos distintos. Confirme peso e dimensões de cada variação na seção Variantes.</p></fieldset>
    <input type="hidden" name="sourceUrl" value={spec.sourceUrl??''} /><textarea hidden name="sourceImages" value={(spec.sourceImages??[]).join('\n')} readOnly />
    <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="text-lg font-semibold">SEO e compliance</legend><label>Título SEO<input name="seoTitle" defaultValue={spec.seo.title} className="ddf-input" /></label><label>Descrição SEO<textarea name="seoDescription" defaultValue={spec.seo.description} className="ddf-input" /></label><label>Notas de compliance<textarea name="complianceNotes" defaultValue={spec.compliance.notes} className="ddf-input" /></label><label>Certificações — uma por linha<textarea name="certifications" defaultValue={spec.compliance.certifications.join('\n')} className="ddf-input" /></label></fieldset>
    <fieldset className="grid gap-4"><legend className="text-lg font-semibold">Variantes e destinos</legend><label>Variantes (JSON: SKU, GTIN/EAN, atributos, dimensões e peso)<textarea name="variants" defaultValue={JSON.stringify(spec.variants,null,2)} className="ddf-input font-mono text-xs" rows={10} /></label><label>Localizações por idioma (JSON)<textarea name="localizations" defaultValue={JSON.stringify(spec.localizations,null,2)} className="ddf-input font-mono text-xs" rows={6} /></label><label>Gaps específicos por destino (JSON)<textarea name="destinationGaps" defaultValue={JSON.stringify(spec.destinationGaps,null,2)} className="ddf-input font-mono text-xs" rows={6} /></label></fieldset>
    <div className="flex gap-3"><button className="ddf-button">Salvar versão</button><button type="button" className="ddf-button secondary" onClick={onCancel}>Cancelar</button></div></form>;
  return <article className="surface space-y-4 p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{product.universalTitle}</h2><p className="text-sm text-gray-600">{product.category || 'Categoria pendente'} · versão {product.version}</p></div><span className="rounded bg-stone-200 px-3 py-1 text-sm">{product.status === 'PRONTO' ? 'Pronto' : 'Em produção'}</span>{product.availability && <span className={`absolute right-2 top-2 rounded-full px-2 py-1 text-[11px] font-bold ${product.availability === 'PRONTA_ENTREGA' ? 'bg-[var(--accent)] text-[var(--accent-ink)]' : 'bg-[var(--ink)] text-[var(--brand-branco)]'}`}>{availabilityLabels[product.availability]}</span>}</div><p>{product.shortDescription || 'Descrição curta pendente.'}</p><div><div className="flex justify-between text-sm"><span>Completude essencial</span><strong>{completion}%</strong></div><div className="mt-2 h-2 bg-stone-200"><div className="h-2 bg-[var(--ink)]" style={{ width: `${completion}%` }} /></div></div>{gaps.length > 0 && <p className="text-sm text-gray-600">Pendências: {gaps.join(', ')}.</p>}
    <p className="whitespace-pre-wrap text-sm">{product.longDescription||'Descrição completa não informada.'}</p><details open><summary className="font-medium">Informações técnicas</summary><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt>Peso do produto</dt><dd>{technical.weightGrams?`${technical.weightGrams} g`:'Não informado pelo fornecedor'}</dd></div><div><dt>Dimensões do produto (C × L × A)</dt><dd>{Object.values(technical.dimensions).every(Boolean)?`${technical.dimensions.lengthCm} × ${technical.dimensions.widthCm} × ${technical.dimensions.heightCm} cm`:'Não informadas pelo fornecedor'}</dd></div><div><dt>Marca / modelo</dt><dd>{[technical.brand,technical.model].filter(Boolean).join(' / ')||'Não informado pelo fornecedor'}</dd></div>{Object.entries({...technical.specifications,...technical.additionalFields}).map(([key,value])=><div key={key}><dt className="font-semibold">{key}</dt><dd>{value||'Não informado pelo fornecedor'}</dd></div>)}</dl><p className="mt-3 text-sm">Características: {technical.features.join('; ')||'Não informadas pelo fornecedor'}</p>{spec.variants.map(variant=><p key={variant.id} className="mt-2 text-sm"><strong>{variant.title}</strong> · {variant.weightGrams?`${variant.weightGrams} g`:'Peso não informado'} · {Object.values(variant.dimensions).every(Boolean)?`${variant.dimensions.lengthCm} × ${variant.dimensions.widthCm} × ${variant.dimensions.heightCm} cm`:'Dimensões não informadas'}</p>)}</details>
    <details><summary className="font-medium">Referências originais preservadas ({spec.sourceImages?.length??0})</summary>{spec.sourceUrl&&<a href={spec.sourceUrl} target="_blank" rel="noopener noreferrer" className="underline">Abrir produto do fornecedor</a>}<div className="mt-3 grid grid-cols-3 gap-2">{(spec.sourceImages??[]).map(url=><a href={url} target="_blank" rel="noopener noreferrer" key={url}><Photo url={url}/></a>)}</div></details>
    <details><summary className="font-medium">Schema universal e gaps</summary><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><p><strong>Materiais:</strong> {spec.materials.join(', ')||'—'}</p><p><strong>Cores:</strong> {spec.colors.join(', ')||'—'}</p><p><strong>Tamanhos:</strong> {spec.sizes.join(', ')||'—'}</p><p><strong>Variantes:</strong> {spec.variants.length}</p>{Object.entries(spec.destinationGaps).map(([destination,items])=><p key={destination}><strong>{destination}:</strong> {items.join(', ')||'Sem gaps'}</p>)}</div></details>
    {(versions?.length??0)>1&&<details><summary className="font-medium">Histórico e comparação de versões</summary><div className="mt-3 space-y-3">{versions?.map((version,index)=>{const newer=versions[index-1];const changes=newer?productVersionDiff(version.snapshot,newer.snapshot):[];return <div className="rounded border border-stone-200 p-3" key={version.version}><div className="flex flex-wrap items-center justify-between gap-2"><strong>Versão {version.version}</strong><span className="text-xs text-gray-600">{new Date(version.at).toLocaleString('pt-BR')}</span>{editable&&product.status==='EM_PRODUCAO'&&version.version!==product.version&&<button className="ddf-button secondary" onClick={()=>onRestore(version.version)}>Restaurar</button>}</div>{changes.length>0&&<ul className="mt-2 list-disc pl-5 text-xs">{changes.map(change=><li key={change.field}>{change.field}: <span className="line-through">{change.before||'vazio'}</span> → {change.after||'vazio'}</li>)}</ul>}</div>})}</div></details>}
    {editable && product.status === 'EM_PRODUCAO' && <div className="flex flex-wrap gap-3"><button className="ddf-button" onClick={onEdit}>Editar cadastro</button><button className="ddf-button secondary" onClick={onReady}>Marcar como pronto</button></div>}{product.status === 'PRONTO' && <p className="text-sm text-green-800">Disponível para futura estratégia de preço e distribuição; ainda não publicado.</p>}</article>;
}
