'use client';

import { useState, useSyncExternalStore } from 'react';
import { emptyIntake, INTAKE_STORAGE_KEY, type IntakeState } from '@/lib/intake';
import { emptyProductFactory, emptyUniversalSpec, PRODUCT_STORAGE_KEY, productGaps, productVersionDiff, type MasterProduct, type ProductFactoryState, type UniversalProductSpec } from '@/lib/product-factory';
import { command, errorMessage, sendCommand, type Command } from '@/lib/command-client';
import { emptyMedia, MEDIA_STORAGE_KEY, type MediaState } from '@/lib/media-factory';
import { baseTaxonomy } from '@/lib/taxonomy';

const eventName = 'ddf-products-change';
function subscribe(callback: () => void) { window.addEventListener('storage', callback); window.addEventListener(eventName, callback); return () => { window.removeEventListener('storage', callback); window.removeEventListener(eventName, callback); }; }
function snapshot() { try { return `${localStorage.getItem(INTAKE_STORAGE_KEY) ?? ''}\n${localStorage.getItem(PRODUCT_STORAGE_KEY) ?? ''}\n${localStorage.getItem(MEDIA_STORAGE_KEY) ?? ''}`; } catch { return 'unavailable'; } }
function parse(raw: string | null) {
  if (!raw) return { intake: emptyIntake, factory: emptyProductFactory, media: emptyMedia };
  const [intakeRaw, factoryRaw, mediaRaw] = raw.split('\n');
  const intake: IntakeState = intakeRaw ? JSON.parse(intakeRaw) : emptyIntake;
  const factory: ProductFactoryState = factoryRaw ? JSON.parse(factoryRaw) : emptyProductFactory;
  const media: MediaState = mediaRaw ? JSON.parse(mediaRaw) : emptyMedia;
  if (intake.version !== 1 || factory.version !== 1 || media.version !== 1 || !Array.isArray(intake.candidates) || !Array.isArray(factory.products) || !Array.isArray(media.assets)) throw new Error();
  return { intake, factory, media };
}
const lines = (value: FormDataEntryValue | null) => String(value ?? '').split('\n');
const cleanLines = (value: FormDataEntryValue | null) => lines(value).map(item=>item.trim()).filter(Boolean);
function parseRecord<T>(value: FormDataEntryValue|null, label:string):T { try { const parsed=JSON.parse(String(value||'{}')); if(!parsed||typeof parsed!=='object') throw new Error(); return parsed as T; } catch { throw new Error(`${label} deve conter JSON válido.`); } }
function readSpec(form:FormData):UniversalProductSpec { return {
  variants: parseRecord<UniversalProductSpec['variants']>(form.get('variants'),'Variantes'), materials:cleanLines(form.get('materials')),colors:cleanLines(form.get('colors')),sizes:cleanLines(form.get('sizes')),
  seo:{title:String(form.get('seoTitle')||''),description:String(form.get('seoDescription')||'')}, compliance:{notes:String(form.get('complianceNotes')||''),certifications:cleanLines(form.get('certifications'))},
  localizations:parseRecord<UniversalProductSpec['localizations']>(form.get('localizations'),'Localizações'),destinationGaps:parseRecord<UniversalProductSpec['destinationGaps']>(form.get('destinationGaps'),'Gaps por destino')}; }

export function ProductFactoryWorkspace({ mode }: { mode: 'factory' | 'catalog' }) {
  const raw = useSyncExternalStore(subscribe, snapshot, () => null);
  let data = { intake: emptyIntake, factory: emptyProductFactory, media: emptyMedia }; let loadError = '';
  try { data = parse(raw); } catch { loadError = 'Os dados locais não puderam ser lidos. A edição foi bloqueada para protegê-los.'; }
  const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const approved = data.intake.candidates.filter(c => c.status === 'APROVADO' && !data.factory.products.some(p => p.candidateId === c.id));
  const products = data.factory.products.filter(p => (mode === 'factory' || p.status === 'PRONTO') && p.universalTitle.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  function act(cmd: Command, success: string) { sendCommand(cmd).then(() => { setError(''); setMessage(success); setEditing(null); }, e => setError(errorMessage(e))); }
  return <div className="space-y-6">
    <header><p className="eyebrow">Produção / cadastro universal</p><h1 className="display-title">{mode === 'factory' ? 'Product Factory' : 'Produtos Disponíveis'}</h1><p className="lede">{mode === 'factory' ? 'Transforme candidatos aprovados em produtos mestres reutilizáveis.' : 'Catálogo de produtos prontos, ainda independentes de publicação.'}</p></header>
    <p className="surface p-4 text-sm">Demonstração local. Produto mestre não contém fornecedor, preço, canal ou publicação. Essas decisões permanecem independentes.</p>
    {(error || loadError) && <p role="alert" className="border border-red-300 bg-red-50 p-4 text-red-800">{error || loadError}</p>}<p role="status" className="text-sm text-green-800">{message}</p>
    {!loadError && mode === 'factory' && <section className="surface p-6"><h2 className="text-xl font-semibold">Fila aprovada</h2><p className="mt-2 text-sm text-gray-600">{approved.length} candidato(s) aguardando início explícito da produção.</p><div className="mt-4 space-y-3">{approved.map(c => <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-stone-200 pt-3"><div><strong>{c.name}</strong><p className="text-sm text-gray-600">Aprovado na triagem</p></div><button className="ddf-button" onClick={() => act(command('products.start', { candidateId: c.id }), 'Produção iniciada. Nenhuma operação externa foi acionada.')}>Iniciar produção</button></div>)}{approved.length === 0 && <p className="mt-4">Nenhum candidato aprovado aguardando produção.</p>}</div></section>}
    <label className="block">Buscar produto<input className="ddf-input" value={query} onChange={e => setQuery(e.target.value)} /></label>
    <p className="text-sm text-gray-600">{products.length} produto(s) nesta área</p>
    {products.length === 0 && <div className="surface p-8"><h2 className="text-lg font-semibold">{mode === 'catalog' ? 'Nenhum produto pronto' : 'A fábrica está vazia'}</h2><p className="mt-2">{mode === 'catalog' ? 'Finalize um cadastro mestre na Product Factory.' : 'Aprove um candidato na Sala de Triagem e inicie sua produção.'}</p></div>}
    {products.map(product => <ProductCard key={product.id} product={product} versions={(data.factory.versions??[]).filter(v=>v.productId===product.id).sort((a,b)=>b.version-a.version)} editable={mode === 'factory'} editing={editing === product.id} onEdit={() => setEditing(product.id)} onCancel={() => setEditing(null)} onSave={form => act(command('products.update', { productId: product.id, universalTitle: String(form.get('title')), category: String(form.get('category')), shortDescription: String(form.get('short')), longDescription: String(form.get('long')), bullets: lines(form.get('bullets')), benefits: lines(form.get('benefits')), tags: String(form.get('tags')).split(','), spec:readSpec(form) }), 'Rascunho salvo e nova versão registrada.')} onRestore={version=>act(command('products.restoreVersion',{productId:product.id,version}),`Versão ${version} restaurada como uma nova versão.`)} onReady={() => act(command('products.markReady', { productId: product.id }), 'Produto marcado como pronto. Nenhuma publicação foi iniciada.')} />)}
  </div>;
}

function ProductCard({ product, versions, editable, editing, onEdit, onCancel, onSave, onRestore, onReady }: { product: MasterProduct; versions:ProductFactoryState['versions']; editable: boolean; editing: boolean; onEdit: () => void; onCancel: () => void; onSave: (form: FormData) => void; onRestore:(version:number)=>void; onReady: () => void }) {
  const gaps = productGaps(product); const completion = Math.round(((6 - gaps.length) / 6) * 100);
  const spec=product.spec??emptyUniversalSpec;
  if (editing) return <form className="surface grid gap-4 p-6" onSubmit={e => { e.preventDefault(); onSave(new FormData(e.currentTarget)); }}><h2 className="text-xl font-semibold">Editar cadastro mestre</h2><label>Título universal<input name="title" defaultValue={product.universalTitle} className="ddf-input" /></label><label>Categoria universal<input name="category" list="ddf-taxonomy" defaultValue={product.category} className="ddf-input" /><datalist id="ddf-taxonomy">{baseTaxonomy.map(node=><option value={node.name} key={node.id}/>)}</datalist></label><label>Descrição curta<textarea name="short" defaultValue={product.shortDescription} className="ddf-input" rows={2} /></label><label>Descrição longa<textarea name="long" defaultValue={product.longDescription} className="ddf-input" rows={4} /></label><label>Bullets — um por linha<textarea name="bullets" defaultValue={product.bullets.join('\n')} className="ddf-input" rows={4} /></label><label>Benefícios — um por linha<textarea name="benefits" defaultValue={product.benefits.join('\n')} className="ddf-input" rows={3} /></label><label>Tags — separadas por vírgula<input name="tags" defaultValue={product.tags.join(', ')} className="ddf-input" /></label>
    <fieldset className="grid gap-4 border-t border-stone-200 pt-4 sm:grid-cols-3"><legend className="text-lg font-semibold">Atributos universais</legend><label>Materiais — um por linha<textarea name="materials" defaultValue={spec.materials.join('\n')} className="ddf-input" /></label><label>Cores — uma por linha<textarea name="colors" defaultValue={spec.colors.join('\n')} className="ddf-input" /></label><label>Tamanhos — um por linha<textarea name="sizes" defaultValue={spec.sizes.join('\n')} className="ddf-input" /></label></fieldset>
    <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="text-lg font-semibold">SEO e compliance</legend><label>Título SEO<input name="seoTitle" defaultValue={spec.seo.title} className="ddf-input" /></label><label>Descrição SEO<textarea name="seoDescription" defaultValue={spec.seo.description} className="ddf-input" /></label><label>Notas de compliance<textarea name="complianceNotes" defaultValue={spec.compliance.notes} className="ddf-input" /></label><label>Certificações — uma por linha<textarea name="certifications" defaultValue={spec.compliance.certifications.join('\n')} className="ddf-input" /></label></fieldset>
    <fieldset className="grid gap-4"><legend className="text-lg font-semibold">Variantes e destinos</legend><label>Variantes (JSON: SKU, GTIN/EAN, atributos, dimensões e peso)<textarea name="variants" defaultValue={JSON.stringify(spec.variants,null,2)} className="ddf-input font-mono text-xs" rows={10} /></label><label>Localizações por idioma (JSON)<textarea name="localizations" defaultValue={JSON.stringify(spec.localizations,null,2)} className="ddf-input font-mono text-xs" rows={6} /></label><label>Gaps específicos por destino (JSON)<textarea name="destinationGaps" defaultValue={JSON.stringify(spec.destinationGaps,null,2)} className="ddf-input font-mono text-xs" rows={6} /></label></fieldset>
    <div className="flex gap-3"><button className="ddf-button">Salvar versão</button><button type="button" className="ddf-button secondary" onClick={onCancel}>Cancelar</button></div></form>;
  return <article className="surface space-y-4 p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{product.universalTitle}</h2><p className="text-sm text-gray-600">{product.category || 'Categoria pendente'} · versão {product.version}</p></div><span className="rounded bg-stone-200 px-3 py-1 text-sm">{product.status === 'PRONTO' ? 'Pronto' : 'Em produção'}</span></div><p>{product.shortDescription || 'Descrição curta pendente.'}</p><div><div className="flex justify-between text-sm"><span>Completude essencial</span><strong>{completion}%</strong></div><div className="mt-2 h-2 bg-stone-200"><div className="h-2 bg-[#ff5b2e]" style={{ width: `${completion}%` }} /></div></div>{gaps.length > 0 && <p className="text-sm text-gray-600">Pendências: {gaps.join(', ')}.</p>}
    <details><summary className="font-medium">Schema universal e gaps</summary><div className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><p><strong>Materiais:</strong> {spec.materials.join(', ')||'—'}</p><p><strong>Cores:</strong> {spec.colors.join(', ')||'—'}</p><p><strong>Tamanhos:</strong> {spec.sizes.join(', ')||'—'}</p><p><strong>Variantes:</strong> {spec.variants.length}</p>{Object.entries(spec.destinationGaps).map(([destination,items])=><p key={destination}><strong>{destination}:</strong> {items.join(', ')||'Sem gaps'}</p>)}</div></details>
    {(versions?.length??0)>1&&<details><summary className="font-medium">Histórico e comparação de versões</summary><div className="mt-3 space-y-3">{versions?.map((version,index)=>{const newer=versions[index-1];const changes=newer?productVersionDiff(version.snapshot,newer.snapshot):[];return <div className="rounded border border-stone-200 p-3" key={version.version}><div className="flex flex-wrap items-center justify-between gap-2"><strong>Versão {version.version}</strong><span className="text-xs text-gray-600">{new Date(version.at).toLocaleString('pt-BR')}</span>{editable&&product.status==='EM_PRODUCAO'&&version.version!==product.version&&<button className="ddf-button secondary" onClick={()=>onRestore(version.version)}>Restaurar</button>}</div>{changes.length>0&&<ul className="mt-2 list-disc pl-5 text-xs">{changes.map(change=><li key={change.field}>{change.field}: <span className="line-through">{change.before||'vazio'}</span> → {change.after||'vazio'}</li>)}</ul>}</div>})}</div></details>}
    {editable && product.status === 'EM_PRODUCAO' && <div className="flex flex-wrap gap-3"><button className="ddf-button" onClick={onEdit}>Editar cadastro</button><button className="ddf-button secondary" onClick={onReady}>Marcar como pronto</button></div>}{product.status === 'PRONTO' && <p className="text-sm text-green-800">Disponível para futura estratégia de preço e distribuição; ainda não publicado.</p>}</article>;
}
