'use client';
/* eslint-disable @next/next/no-img-element -- Authenticated original reference photos. */
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { modelMeasureLabels,type ModelMeasure,type RealModel } from '@/lib/real-models';
export function RealModelsWorkspace(){
  const[models,setModels]=useState<RealModel[]>([]);const[selected,setSelected]=useState<RealModel|null>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;fetch('/api/real-models',{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error('Não foi possível carregar os modelos.');return response.json();}).then(data=>{if(active)setModels(data.models);}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[]);
  async function save(){if(!selected)return;setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/real-models',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(selected)});const data=await response.json();if(!response.ok)throw new Error(data.error);setSelected(data.model);setModels(items=>[data.model,...items.filter(item=>item.id!==data.model.id)]);setNotice('Pasta do modelo salva com fotos e medidas.');}catch(err){setError(err instanceof Error?err.message:'Falha ao salvar.');}finally{setBusy(false);}}
  return <div className="space-y-6"><header><p className="eyebrow">Media Factory / referências humanas</p><h1 className="display-title">Catálogo de modelos reais</h1><p className="lede">Uma pasta por pessoa: fotos reais com roupa neutra e medidas para vestir peças com IA.</p></header><Link href="/media-factory" className="underline">Voltar à central de mídia</Link><p className="surface p-4 text-sm">As fotos dos modelos são referências separadas das fotos dos produtos. A composição de roupas exige IA com edição por referência e validação de identidade, detalhes da peça e proporções; sua geração aguarda essa capacidade no gateway central. A fotografia dos óculos continua em seu fluxo próprio.</p>{error&&<p role="alert" className="text-red-800">{error}</p>}<p role="status">{notice}</p><button className="ddf-button" disabled={busy} onClick={()=>{setSelected({id:crypto.randomUUID(),name:'',brand:'Dive',measurements:{},photos:[],notes:'',revision:0});setNotice('');}}>Criar pasta de modelo</button><section className="grid gap-3 md:grid-cols-4 xl:grid-cols-5">{models.map(model=><button key={model.id} className="surface p-4 text-left" onClick={()=>setSelected(structuredClone(model))}>{model.photos[0]&&<img className="h-36 w-full object-contain" src={model.photos[0].url} alt={model.name}/>}<h2 className="font-semibold">{model.name}</h2><p className="text-sm">{model.brand} · {model.photos.length} fotos</p><p className="text-xs">{model.measurements.heightCm??'—'} cm · {model.measurements.weightKg??'—'} kg</p></button>)}</section>{!models.length&&<p>Crie sua primeira pasta e acrescente suas fotos neutras e medidas.</p>}
    {selected&&<section className="surface space-y-4 p-5"><h2 className="text-xl font-semibold">{selected.name||'Novo modelo'}</h2><div className="grid gap-4 md:grid-cols-3"><label>Nome<input className="ddf-input" value={selected.name} maxLength={160} onChange={event=>setSelected({...selected,name:event.target.value})}/></label><label>Marca<input className="ddf-input" value={selected.brand} maxLength={120} onChange={event=>setSelected({...selected,brand:event.target.value})}/></label>{(Object.entries(modelMeasureLabels) as [ModelMeasure,string][]).map(([key,label])=><label key={key}>{label}<input className="ddf-input" type="number" min="0.1" max="500" step="0.1" value={selected.measurements[key]??''} onChange={event=>setSelected({...selected,measurements:{...selected.measurements,[key]:event.target.value===''?null:Number(event.target.value)}})}/></label>)}</div><label className="block">Observações de postura, proporções e roupa neutra<textarea className="ddf-input" value={selected.notes} maxLength={6000} onChange={event=>setSelected({...selected,notes:event.target.value})}/></label>
    <form className="grid gap-3 md:grid-cols-3" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);setBusy(true);setError('');try{const upload=new FormData();upload.set('file',fields.get('file')!);const response=await fetch('/api/media',{method:'POST',body:upload});const data=await response.json();if(!response.ok)throw new Error(data.error);setSelected({...selected,photos:[...selected.photos,{url:data.url,checksum:data.checksum,mimeType:data.mimeType,bytes:data.bytes,angle:String(fields.get('angle'))}]});form.reset();setNotice('Foto armazenada. Salve a pasta para vincular ao modelo.');}catch(err){setError(err instanceof Error?err.message:'Upload indisponível.');}finally{setBusy(false);}}}><label>Foto real neutra (até 10 MB)<input className="ddf-input" required type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif"/></label><label>Ângulo / postura<input className="ddf-input" name="angle" required maxLength={160} placeholder="Frente, corpo inteiro"/></label><button className="ddf-button" disabled={busy||selected.photos.length>=40}>Adicionar foto neutra</button></form><div className="grid gap-3 md:grid-cols-4">{selected.photos.map((photo,index)=><figure className="border p-3" key={`${photo.url}-${index}`}><img className="h-40 w-full object-contain" src={photo.url} alt={`${selected.name}: ${photo.angle}`}/><figcaption>{photo.angle}</figcaption><button className="text-sm underline" disabled={busy} onClick={()=>setSelected({...selected,photos:selected.photos.filter((_,i)=>i!==index)})}>Retirar desta pasta</button></figure>)}</div><button className="ddf-button" disabled={busy||!selected.name.trim()||!selected.brand.trim()} onClick={save}>{busy?'Salvando…':'Salvar pasta do modelo'}</button></section>}
  </div>;
}
