'use client';
import { useEffect, useState } from 'react';
const stores = [
  ['intake','ddf.intake.demo.v1','ddf-intake-change'],['products','ddf.products.demo.v1','ddf-products-change'],
  ['media','ddf.media.demo.v1','ddf-media-change'],['pricing','ddf.pricing.demo.v1','ddf-pricing-change'],
  ['connectors','ddf.connectors.demo.v1','ddf-connectors-change'],['orders','ddf.orders.demo.v1','ddf-orders-change'],
] as const;
export function ServerStateBridge(){const[state,setState]=useState<'loading'|'online'|'offline'|'conflict'>('loading');useEffect(()=>{const revisions=new Map<string,number|null>();let active=true;
  Promise.all(stores.map(async([namespace,key,event])=>{const response=await fetch(`/api/state/${namespace}`,{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();revisions.set(namespace,data.revision);if(data.payload){localStorage.setItem(key,JSON.stringify(data.payload));window.dispatchEvent(new Event(event));}else{const local=localStorage.getItem(key);if(local){const saved=await fetch(`/api/state/${namespace}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({payload:JSON.parse(local),revision:null})});if(saved.ok)revisions.set(namespace,(await saved.json()).revision);}}})).then(()=>active&&setState('online')).catch(()=>active&&setState('offline'));
  const cleanups=stores.map(([namespace,key,event])=>{const sync=async()=>{const raw=localStorage.getItem(key);if(!raw)return;try{const response=await fetch(`/api/state/${namespace}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({payload:JSON.parse(raw),revision:revisions.get(namespace)??null})});if(response.status===409){setState('conflict');return;}if(!response.ok)throw new Error();revisions.set(namespace,(await response.json()).revision);setState('online');}catch{setState('offline')}};window.addEventListener(event,sync);return()=>window.removeEventListener(event,sync)});return()=>{active=false;cleanups.forEach(fn=>fn())}},[]);
 return <div className={`fixed bottom-3 right-3 z-50 rounded px-3 py-2 text-xs font-semibold shadow ${state==='online'?'bg-green-100 text-green-900':state==='loading'?'bg-stone-200 text-stone-700':'bg-red-100 text-red-900'}`} role="status">{state==='online'?'Banco sincronizado':state==='loading'?'Conectando ao banco…':state==='conflict'?'Conflito de versão':'Modo local — banco indisponível'}</div>}
